<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'api_platform.listener.view.respond' shared service.

return $this->services['api_platform.listener.view.respond'] = new \ApiPlatform\Core\EventListener\RespondListener();
