<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'doctrine.orm.default_entity_manager' shared service.

$a = new \Doctrine\ORM\Configuration();

$b = new \Doctrine\Common\Persistence\Mapping\Driver\MappingDriverChain();

$c = new \Doctrine\ORM\Mapping\Driver\AnnotationDriver(${($_ = isset($this->services['annotation_reader']) ? $this->services['annotation_reader'] : $this->getAnnotationReaderService()) && false ?: '_'}, [0 => ($this->targetDirs[4].'/vendor/gedmo/doctrine-extensions/lib/Gedmo/Tree/Entity'), 1 => ($this->targetDirs[4].'/src/PartKeepr/CronLoggerBundle/Entity'), 2 => ($this->targetDirs[4].'/src/PartKeepr/CategoryBundle/Entity'), 3 => ($this->targetDirs[4].'/src/PartKeepr/UploadedFileBundle/Entity'), 4 => ($this->targetDirs[4].'/src/PartKeepr/FrontendBundle/Entity'), 5 => ($this->targetDirs[4].'/src/PartKeepr/SiPrefixBundle/Entity'), 6 => ($this->targetDirs[4].'/src/PartKeepr/AuthBundle/Entity'), 7 => ($this->targetDirs[4].'/src/PartKeepr/CoreBundle/Entity'), 8 => ($this->targetDirs[4].'/src/PartKeepr/FootprintBundle/Entity'), 9 => ($this->targetDirs[4].'/src/PartKeepr/UnitBundle/Entity'), 10 => ($this->targetDirs[4].'/src/PartKeepr/PartBundle/Entity'), 11 => ($this->targetDirs[4].'/src/PartKeepr/StockBundle/Entity'), 12 => ($this->targetDirs[4].'/src/PartKeepr/DistributorBundle/Entity'), 13 => ($this->targetDirs[4].'/src/PartKeepr/ManufacturerBundle/Entity'), 14 => ($this->targetDirs[4].'/src/PartKeepr/ImageBundle/Entity'), 15 => ($this->targetDirs[4].'/src/PartKeepr/ProjectBundle/Entity'), 16 => ($this->targetDirs[4].'/src/PartKeepr/StorageLocationBundle/Entity'), 17 => ($this->targetDirs[4].'/src/PartKeepr/TipOfTheDayBundle/Entity'), 18 => ($this->targetDirs[4].'/src/PartKeepr/StatisticBundle/Entity'), 19 => ($this->targetDirs[4].'/src/PartKeepr/SystemPreferenceBundle/Entity'), 20 => ($this->targetDirs[4].'/src/PartKeepr/ImportBundle/Entity'), 21 => ($this->targetDirs[4].'/src/PartKeepr/BatchJobBundle/Entity')]);

$b->addDriver($c, 'Gedmo\\Tree\\Entity');
$b->addDriver($c, 'PartKeepr\\CronLoggerBundle\\Entity');
$b->addDriver($c, 'PartKeepr\\CategoryBundle\\Entity');
$b->addDriver($c, 'PartKeepr\\UploadedFileBundle\\Entity');
$b->addDriver($c, 'PartKeepr\\FrontendBundle\\Entity');
$b->addDriver($c, 'PartKeepr\\SiPrefixBundle\\Entity');
$b->addDriver($c, 'PartKeepr\\AuthBundle\\Entity');
$b->addDriver($c, 'PartKeepr\\CoreBundle\\Entity');
$b->addDriver($c, 'PartKeepr\\FootprintBundle\\Entity');
$b->addDriver($c, 'PartKeepr\\UnitBundle\\Entity');
$b->addDriver($c, 'PartKeepr\\PartBundle\\Entity');
$b->addDriver($c, 'PartKeepr\\StockBundle\\Entity');
$b->addDriver($c, 'PartKeepr\\DistributorBundle\\Entity');
$b->addDriver($c, 'PartKeepr\\ManufacturerBundle\\Entity');
$b->addDriver($c, 'PartKeepr\\ImageBundle\\Entity');
$b->addDriver($c, 'PartKeepr\\ProjectBundle\\Entity');
$b->addDriver($c, 'PartKeepr\\StorageLocationBundle\\Entity');
$b->addDriver($c, 'PartKeepr\\TipOfTheDayBundle\\Entity');
$b->addDriver($c, 'PartKeepr\\StatisticBundle\\Entity');
$b->addDriver($c, 'PartKeepr\\SystemPreferenceBundle\\Entity');
$b->addDriver($c, 'PartKeepr\\ImportBundle\\Entity');
$b->addDriver($c, 'PartKeepr\\BatchJobBundle\\Entity');
$b->addDriver(new \Doctrine\ORM\Mapping\Driver\XmlDriver(new \Doctrine\Common\Persistence\Mapping\Driver\SymfonyFileLocator([($this->targetDirs[4].'/vendor/friendsofsymfony/user-bundle/Resources/config/doctrine-mapping') => 'FOS\\UserBundle\\Model'], '.orm.xml')), 'FOS\\UserBundle\\Model');

$a->setEntityNamespaces(['GedmoTree' => 'Gedmo\\Tree\\Entity', 'PartKeeprCronLoggerBundle' => 'PartKeepr\\CronLoggerBundle\\Entity', 'PartKeeprCategoryBundle' => 'PartKeepr\\CategoryBundle\\Entity', 'PartKeeprUploadedFileBundle' => 'PartKeepr\\UploadedFileBundle\\Entity', 'PartKeeprFrontendBundle' => 'PartKeepr\\FrontendBundle\\Entity', 'PartKeeprSiPrefixBundle' => 'PartKeepr\\SiPrefixBundle\\Entity', 'PartKeeprAuthBundle' => 'PartKeepr\\AuthBundle\\Entity', 'PartKeeprCoreBundle' => 'PartKeepr\\CoreBundle\\Entity', 'PartKeeprFootprintBundle' => 'PartKeepr\\FootprintBundle\\Entity', 'PartKeeprUnitBundle' => 'PartKeepr\\UnitBundle\\Entity', 'PartKeeprPartBundle' => 'PartKeepr\\PartBundle\\Entity', 'PartKeeprStockBundle' => 'PartKeepr\\StockBundle\\Entity', 'PartKeeprDistributorBundle' => 'PartKeepr\\DistributorBundle\\Entity', 'PartKeeprManufacturerBundle' => 'PartKeepr\\ManufacturerBundle\\Entity', 'PartKeeprImageBundle' => 'PartKeepr\\ImageBundle\\Entity', 'PartKeeprProjectBundle' => 'PartKeepr\\ProjectBundle\\Entity', 'PartKeeprStorageLocationBundle' => 'PartKeepr\\StorageLocationBundle\\Entity', 'PartKeeprTipOfTheDayBundle' => 'PartKeepr\\TipOfTheDayBundle\\Entity', 'PartKeeprStatisticBundle' => 'PartKeepr\\StatisticBundle\\Entity', 'PartKeeprSystemPreferenceBundle' => 'PartKeepr\\SystemPreferenceBundle\\Entity', 'PartKeeprImportBundle' => 'PartKeepr\\ImportBundle\\Entity', 'PartKeeprBatchJobBundle' => 'PartKeepr\\BatchJobBundle\\Entity']);
$a->setMetadataCacheImpl(${($_ = isset($this->services['doctrine_cache.providers.doctrine.orm.default_metadata_cache']) ? $this->services['doctrine_cache.providers.doctrine.orm.default_metadata_cache'] : $this->load('getDoctrineCache_Providers_Doctrine_Orm_DefaultMetadataCacheService.php')) && false ?: '_'});
$a->setQueryCacheImpl(${($_ = isset($this->services['doctrine_cache.providers.doctrine.orm.default_query_cache']) ? $this->services['doctrine_cache.providers.doctrine.orm.default_query_cache'] : $this->load('getDoctrineCache_Providers_Doctrine_Orm_DefaultQueryCacheService.php')) && false ?: '_'});
$a->setResultCacheImpl(${($_ = isset($this->services['doctrine_cache.providers.doctrine.orm.default_result_cache']) ? $this->services['doctrine_cache.providers.doctrine.orm.default_result_cache'] : $this->load('getDoctrineCache_Providers_Doctrine_Orm_DefaultResultCacheService.php')) && false ?: '_'});
$a->setMetadataDriverImpl($b);
$a->setProxyDir(($this->targetDirs[0].'/doctrine/orm/Proxies'));
$a->setProxyNamespace('Proxies');
$a->setAutoGenerateProxyClasses(true);
$a->setClassMetadataFactoryName('Doctrine\\ORM\\Mapping\\ClassMetadataFactory');
$a->setDefaultRepositoryClassName('Doctrine\\ORM\\EntityRepository');
$a->setNamingStrategy(new \Doctrine\ORM\Mapping\DefaultNamingStrategy());
$a->setQuoteStrategy(new \Doctrine\ORM\Mapping\DefaultQuoteStrategy());
$a->setEntityListenerResolver(${($_ = isset($this->services['doctrine.orm.default_entity_listener_resolver']) ? $this->services['doctrine.orm.default_entity_listener_resolver'] : ($this->services['doctrine.orm.default_entity_listener_resolver'] = new \Doctrine\Bundle\DoctrineBundle\Mapping\ContainerAwareEntityListenerResolver($this))) && false ?: '_'});
$a->setRepositoryFactory(new \Doctrine\Bundle\DoctrineBundle\Repository\ContainerRepositoryFactory(${($_ = isset($this->services['service_locator.sr6ctxe']) ? $this->services['service_locator.sr6ctxe'] : ($this->services['service_locator.sr6ctxe'] = new \Symfony\Component\DependencyInjection\ServiceLocator([]))) && false ?: '_'}));

$this->services['doctrine.orm.default_entity_manager'] = $instance = \Doctrine\ORM\EntityManager::create(${($_ = isset($this->services['doctrine.dbal.default_connection']) ? $this->services['doctrine.dbal.default_connection'] : $this->load('getDoctrine_Dbal_DefaultConnectionService.php')) && false ?: '_'}, $a);

${($_ = isset($this->services['doctrine.orm.default_manager_configurator']) ? $this->services['doctrine.orm.default_manager_configurator'] : ($this->services['doctrine.orm.default_manager_configurator'] = new \Doctrine\Bundle\DoctrineBundle\ManagerConfigurator([], []))) && false ?: '_'}->configure($instance);

return $instance;
