<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'fos_user.util.token_generator' shared service.

return $this->services['fos_user.util.token_generator'] = new \FOS\UserBundle\Util\TokenGenerator();
