<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'partkeepr.part_service' shared service.

return $this->services['partkeepr.part_service'] = new \PartKeepr\PartBundle\Services\PartService(${($_ = isset($this->services['doctrine.orm.default_entity_manager']) ? $this->services['doctrine.orm.default_entity_manager'] : $this->load('getDoctrine_Orm_DefaultEntityManagerService.php')) && false ?: '_'}, ${($_ = isset($this->services['doctrine_filter_service']) ? $this->services['doctrine_filter_service'] : $this->load('getDoctrineFilterServiceService.php')) && false ?: '_'}, false, false);
