<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'partkeepr_mimetype_icon_service' shared service.

return $this->services['partkeepr_mimetype_icon_service'] = new \PartKeepr\MimetypeIconsBundle\Services\MimetypeIconService($this);
