<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'translation.loader.po' shared service.

return $this->services['translation.loader.po'] = new \Symfony\Component\Translation\Loader\PoFileLoader();
