<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'xlsx_responder_view_listener' shared service.

return $this->services['xlsx_responder_view_listener'] = new \PartKeepr\ExportBundle\EventListener\XmlExcelResponderViewListener();
