<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLev13j0\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLev13j0/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerLev13j0.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerLev13j0\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerLev13j0\appDevDebugProjectContainer([
    'container.build_hash' => 'Lev13j0',
    'container.build_id' => '171c4a11',
    'container.build_time' => 1614107330,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLev13j0');
