<?php
/**
 * Export to PHP Array plugin for PHPMyAdmin
 * @author Geoffray Warnants
 * @version 0.2b
 */

//
// Database "partdb"
//

// partdb.parts
$parts = array(
  array('id'=>1,'id_category'=>7,'name'=>'L7805CV','instock'=>83,'mininstock'=>0,'comment'=>'neu, ST Microelectronics','id_footprint'=>2,'id_storeloc'=>1,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>2,'id_category'=>8,'name'=>'MC7805CT','instock'=>51,'mininstock'=>0,'comment'=>'neu, Motorola','id_footprint'=>2,'id_storeloc'=>2,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>3,'id_category'=>8,'name'=>'MC78T05CT','instock'=>10,'mininstock'=>0,'comment'=>'neu, Motorola','id_footprint'=>2,'id_storeloc'=>3,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>4,'id_category'=>8,'name'=>'MC7808AC','instock'=>24,'mininstock'=>0,'comment'=>'neu, Samsung','id_footprint'=>2,'id_storeloc'=>4,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>5,'id_category'=>8,'name'=>'L7812CV','instock'=>88,'mininstock'=>0,'comment'=>'neu, ST Microelectronics','id_footprint'=>2,'id_storeloc'=>5,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>6,'id_category'=>8,'name'=>'L78S24CV','instock'=>26,'mininstock'=>0,'comment'=>'neu, ST Microelectronics','id_footprint'=>2,'id_storeloc'=>6,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>7,'id_category'=>7,'name'=>'L7905CV','instock'=>1,'mininstock'=>0,'comment'=>'neu, SGS-Thomson Microelectonics','id_footprint'=>2,'id_storeloc'=>12,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>8,'id_category'=>8,'name'=>'79L05A','instock'=>16,'mininstock'=>0,'comment'=>'neu,','id_footprint'=>3,'id_storeloc'=>7,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>9,'id_category'=>16,'name'=>'33nF 100V MKS-3','instock'=>136,'mininstock'=>0,'comment'=>'neu, WIMA','id_footprint'=>6,'id_storeloc'=>8,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>10,'id_category'=>22,'name'=>'47µF 35V radial','instock'=>90,'mininstock'=>0,'comment'=>'neu, Cosonic','id_footprint'=>5,'id_storeloc'=>35,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>11,'id_category'=>22,'name'=>'1000µF 25V radial','instock'=>52,'mininstock'=>0,'comment'=>'neu, Jamicon','id_footprint'=>5,'id_storeloc'=>19,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>12,'id_category'=>22,'name'=>'1µF 16V Radial','instock'=>17,'mininstock'=>0,'comment'=>'neu, Lelon','id_footprint'=>5,'id_storeloc'=>20,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>13,'id_category'=>22,'name'=>'10µF 63V radial','instock'=>90,'mininstock'=>0,'comment'=>'neu, SAMHWA','id_footprint'=>5,'id_storeloc'=>34,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>14,'id_category'=>22,'name'=>'22µF 63V radial','instock'=>92,'mininstock'=>0,'comment'=>'neu, Rubycon','id_footprint'=>5,'id_storeloc'=>36,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>15,'id_category'=>22,'name'=>'470µF 16V axial','instock'=>10,'mininstock'=>0,'comment'=>'neu, Frolyt','id_footprint'=>8,'id_storeloc'=>38,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>16,'id_category'=>22,'name'=>'820nF 250V MKC1863 axial','instock'=>14,'mininstock'=>0,'comment'=>'neu, EAO','id_footprint'=>8,'id_storeloc'=>18,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>17,'id_category'=>22,'name'=>'20µF 350V axial','instock'=>10,'mininstock'=>0,'comment'=>'neu, RFT','id_footprint'=>8,'id_storeloc'=>37,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>18,'id_category'=>60,'name'=>'Distanzhülsen 5mm Kunststoff','instock'=>8,'mininstock'=>0,'comment'=>'neu','id_footprint'=>8,'id_storeloc'=>9,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>19,'id_category'=>60,'name'=>'Distanzhülsen 10mm Kunststoff','instock'=>21,'mininstock'=>0,'comment'=>'neu','id_footprint'=>8,'id_storeloc'=>9,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>20,'id_category'=>60,'name'=>'Distanzhülsen 15mm Kunststoff','instock'=>10,'mininstock'=>0,'comment'=>'neu','id_footprint'=>8,'id_storeloc'=>9,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>21,'id_category'=>60,'name'=>'Distanzhülsen 20mm Kunststoff','instock'=>10,'mininstock'=>0,'comment'=>'neu','id_footprint'=>8,'id_storeloc'=>9,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>22,'id_category'=>60,'name'=>'Distanzhülsen 24mm Kunststoff','instock'=>10,'mininstock'=>0,'comment'=>'neu','id_footprint'=>8,'id_storeloc'=>9,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>23,'id_category'=>60,'name'=>'Distanzhülsen 30mm Kunststoff','instock'=>10,'mininstock'=>0,'comment'=>'neu','id_footprint'=>8,'id_storeloc'=>9,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>24,'id_category'=>60,'name'=>'Distanzhülsen 35mm Kunststoff','instock'=>10,'mininstock'=>0,'comment'=>'neu','id_footprint'=>8,'id_storeloc'=>9,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>25,'id_category'=>60,'name'=>'Distanzhülsen 11mm Metall','instock'=>17,'mininstock'=>0,'comment'=>'neu','id_footprint'=>8,'id_storeloc'=>9,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>26,'id_category'=>60,'name'=>'Distanzhülsen 3mm Metall','instock'=>8,'mininstock'=>0,'comment'=>'neu','id_footprint'=>8,'id_storeloc'=>9,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>27,'id_category'=>60,'name'=>'Distanzhülsen 6mm Kunststoff','instock'=>2,'mininstock'=>0,'comment'=>'neu','id_footprint'=>8,'id_storeloc'=>9,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>28,'id_category'=>176,'name'=>'IC-Sockel 6-polig, gedreht','instock'=>3,'mininstock'=>0,'comment'=>'neu','id_footprint'=>8,'id_storeloc'=>10,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>29,'id_category'=>176,'name'=>'IC-Sockel 8-polig, gedreht','instock'=>9,'mininstock'=>0,'comment'=>'neu','id_footprint'=>8,'id_storeloc'=>10,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>30,'id_category'=>176,'name'=>'IC-Sockel 14-polig, gedreht','instock'=>4,'mininstock'=>0,'comment'=>'neu','id_footprint'=>8,'id_storeloc'=>10,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>31,'id_category'=>176,'name'=>'IC-Sockel 16-polig, gedreht','instock'=>22,'mininstock'=>0,'comment'=>'neu','id_footprint'=>8,'id_storeloc'=>10,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>32,'id_category'=>176,'name'=>'IC-Sockel 6-polig, Federkontakt','instock'=>1,'mininstock'=>0,'comment'=>'neu','id_footprint'=>8,'id_storeloc'=>10,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>33,'id_category'=>176,'name'=>'IC-Sockel 8-polig, Federkontakt','instock'=>6,'mininstock'=>0,'comment'=>'neu','id_footprint'=>8,'id_storeloc'=>10,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>34,'id_category'=>176,'name'=>'IC-Sockel 14-polig, Federkontakt','instock'=>34,'mininstock'=>0,'comment'=>'neu','id_footprint'=>8,'id_storeloc'=>10,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>35,'id_category'=>176,'name'=>'IC-Sockel 16-polig, Federkontakt','instock'=>28,'mininstock'=>0,'comment'=>'','id_footprint'=>8,'id_storeloc'=>10,'id_supplier'=>1,'supplierpartnr'=>'neu'),
  array('id'=>36,'id_category'=>176,'name'=>'IC-Sockel 20-polig, Federkontakt','instock'=>4,'mininstock'=>0,'comment'=>'neu','id_footprint'=>8,'id_storeloc'=>10,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>37,'id_category'=>176,'name'=>'IC-Sockel 14-polig, 90 Grad, gedreht','instock'=>13,'mininstock'=>0,'comment'=>'gebraucht','id_footprint'=>8,'id_storeloc'=>10,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>38,'id_category'=>7,'name'=>'Carrier IC-Fassung / Präzisionskontak vergoldet gedreht ','instock'=>34,'mininstock'=>0,'comment'=>'','id_footprint'=>4,'id_storeloc'=>10,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>39,'id_category'=>68,'name'=>'Quarzoszillator 18,432MHz','instock'=>11,'mininstock'=>0,'comment'=>'gebraucht','id_footprint'=>8,'id_storeloc'=>11,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>40,'id_category'=>68,'name'=>'Quarzoszillator 10,000000MHz','instock'=>1,'mininstock'=>0,'comment'=>'gebraucht','id_footprint'=>8,'id_storeloc'=>11,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>41,'id_category'=>68,'name'=>'Standardquarz 4,000000MHz','instock'=>2,'mininstock'=>0,'comment'=>'gebraucht','id_footprint'=>8,'id_storeloc'=>11,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>42,'id_category'=>68,'name'=>'Standardquarz 24,00000MHz','instock'=>3,'mininstock'=>0,'comment'=>'gebraucht','id_footprint'=>8,'id_storeloc'=>11,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>43,'id_category'=>68,'name'=>'Standardquarz 4,433619MHz','instock'=>2,'mininstock'=>0,'comment'=>'gebraucht','id_footprint'=>8,'id_storeloc'=>11,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>44,'id_category'=>68,'name'=>'Standardquarz 16,000000MHz','instock'=>17,'mininstock'=>0,'comment'=>'gebraucht','id_footprint'=>8,'id_storeloc'=>11,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>45,'id_category'=>186,'name'=>'L200C','instock'=>4,'mininstock'=>0,'comment'=>'neu, ST Microelektronics','id_footprint'=>9,'id_storeloc'=>12,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>46,'id_category'=>186,'name'=>'L200C','instock'=>1,'mininstock'=>0,'comment'=>'neu, SGS-Thomson Microelectonics','id_footprint'=>9,'id_storeloc'=>12,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>47,'id_category'=>186,'name'=>'UA7805C','instock'=>4,'mininstock'=>0,'comment'=>'neu, Texas Instruments','id_footprint'=>2,'id_storeloc'=>12,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>48,'id_category'=>186,'name'=>'7806CV','instock'=>8,'mininstock'=>0,'comment'=>'neu, TSL','id_footprint'=>2,'id_storeloc'=>12,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>49,'id_category'=>186,'name'=>'7808 mix','instock'=>1,'mininstock'=>0,'comment'=>'gebraucht','id_footprint'=>2,'id_storeloc'=>12,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>50,'id_category'=>186,'name'=>'UA7808CSP','instock'=>2,'mininstock'=>0,'comment'=>'neu, Thomson-CSF','id_footprint'=>2,'id_storeloc'=>12,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>51,'id_category'=>186,'name'=>'L7809CV','instock'=>1,'mininstock'=>0,'comment'=>'neu, ST Microelektronics','id_footprint'=>2,'id_storeloc'=>12,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>52,'id_category'=>186,'name'=>'7812 mix','instock'=>4,'mininstock'=>0,'comment'=>'gebraucht','id_footprint'=>2,'id_storeloc'=>12,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>53,'id_category'=>186,'name'=>'UA7812C','instock'=>5,'mininstock'=>0,'comment'=>'neu, Texas Instruments','id_footprint'=>2,'id_storeloc'=>12,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>54,'id_category'=>186,'name'=>'7815 mix','instock'=>3,'mininstock'=>0,'comment'=>'gebraucht','id_footprint'=>2,'id_storeloc'=>12,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>55,'id_category'=>186,'name'=>'UA7815CSP','instock'=>1,'mininstock'=>0,'comment'=>'neu, ST Microelektronics ','id_footprint'=>2,'id_storeloc'=>12,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>56,'id_category'=>186,'name'=>'L7815C-V','instock'=>1,'mininstock'=>0,'comment'=>'neu, ST Microelektronics ','id_footprint'=>2,'id_storeloc'=>12,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>57,'id_category'=>186,'name'=>'L7815CV','instock'=>1,'mininstock'=>0,'comment'=>'neu, SGS-Thomson Microelectonics ','id_footprint'=>2,'id_storeloc'=>12,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>58,'id_category'=>186,'name'=>'7905 mix','instock'=>1,'mininstock'=>0,'comment'=>'gebraucht','id_footprint'=>2,'id_storeloc'=>12,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>59,'id_category'=>186,'name'=>'L7905CV','instock'=>1,'mininstock'=>0,'comment'=>'neu, ST Microelectronics','id_footprint'=>2,'id_storeloc'=>12,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>60,'id_category'=>186,'name'=>'L7905CV','instock'=>1,'mininstock'=>0,'comment'=>'neu, SGS-Thomson Microelectonics','id_footprint'=>2,'id_storeloc'=>12,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>61,'id_category'=>186,'name'=>'MC7906CT','instock'=>2,'mininstock'=>0,'comment'=>'neu, Motorola','id_footprint'=>2,'id_storeloc'=>12,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>62,'id_category'=>186,'name'=>'7912 mix','instock'=>1,'mininstock'=>0,'comment'=>'gebraucht','id_footprint'=>2,'id_storeloc'=>12,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>63,'id_category'=>186,'name'=>'7915 mix','instock'=>3,'mininstock'=>0,'comment'=>'gebraucht','id_footprint'=>2,'id_storeloc'=>12,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>64,'id_category'=>77,'name'=>'ZM1000R','instock'=>13,'mininstock'=>0,'comment'=>'gebraucht, Valvo / (Philips)','id_footprint'=>8,'id_storeloc'=>21,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>65,'id_category'=>112,'name'=>'1N4148','instock'=>67,'mininstock'=>0,'comment'=>'neu','id_footprint'=>8,'id_storeloc'=>13,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>66,'id_category'=>112,'name'=>'1N4007','instock'=>28,'mininstock'=>0,'comment'=>'neu','id_footprint'=>8,'id_storeloc'=>13,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>67,'id_category'=>112,'name'=>'1N4001','instock'=>50,'mininstock'=>0,'comment'=>'neu','id_footprint'=>8,'id_storeloc'=>13,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>68,'id_category'=>112,'name'=>'1N4004','instock'=>20,'mininstock'=>0,'comment'=>'neu','id_footprint'=>8,'id_storeloc'=>13,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>69,'id_category'=>112,'name'=>'1N4003','instock'=>50,'mininstock'=>0,'comment'=>'neu','id_footprint'=>8,'id_storeloc'=>13,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>70,'id_category'=>100,'name'=>'B0580','instock'=>62,'mininstock'=>0,'comment'=>'neu, Siemens ,(0,4A Schottky?)','id_footprint'=>6,'id_storeloc'=>39,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>71,'id_category'=>145,'name'=>'27µF 250V MKP1841','instock'=>26,'mininstock'=>1,'comment'=>'neu, ERO','id_footprint'=>8,'id_storeloc'=>40,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>72,'id_category'=>141,'name'=>'220nF 160V MKT','instock'=>29,'mininstock'=>0,'comment'=>'neu, ERO','id_footprint'=>7,'id_storeloc'=>41,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>73,'id_category'=>186,'name'=>'LM320K-15','instock'=>3,'mininstock'=>0,'comment'=>'','id_footprint'=>11,'id_storeloc'=>22,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>74,'id_category'=>186,'name'=>'LM320K-5','instock'=>1,'mininstock'=>0,'comment'=>'','id_footprint'=>11,'id_storeloc'=>22,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>75,'id_category'=>186,'name'=>'LM320K-12','instock'=>1,'mininstock'=>0,'comment'=>'','id_footprint'=>11,'id_storeloc'=>22,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>76,'id_category'=>186,'name'=>'LM340K-15','instock'=>3,'mininstock'=>0,'comment'=>'','id_footprint'=>11,'id_storeloc'=>22,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>77,'id_category'=>106,'name'=>'2N3055','instock'=>4,'mininstock'=>0,'comment'=>'','id_footprint'=>11,'id_storeloc'=>22,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>78,'id_category'=>107,'name'=>'MJ900','instock'=>3,'mininstock'=>0,'comment'=>'','id_footprint'=>11,'id_storeloc'=>23,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>79,'id_category'=>106,'name'=>'MJ3000','instock'=>2,'mininstock'=>0,'comment'=>'','id_footprint'=>11,'id_storeloc'=>23,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>80,'id_category'=>186,'name'=>'SG7815ACK','instock'=>3,'mininstock'=>0,'comment'=>'','id_footprint'=>11,'id_storeloc'=>23,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>81,'id_category'=>171,'name'=>'SUB-D 15-polig Stecker','instock'=>2,'mininstock'=>0,'comment'=>'','id_footprint'=>8,'id_storeloc'=>24,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>82,'id_category'=>171,'name'=>'SUB-D 15-polig Stecker High Density 3-reihig','instock'=>7,'mininstock'=>0,'comment'=>'','id_footprint'=>8,'id_storeloc'=>24,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>83,'id_category'=>171,'name'=>'SUB-D 15-polig Buchse High Density 3-reihig','instock'=>7,'mininstock'=>0,'comment'=>'','id_footprint'=>8,'id_storeloc'=>24,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>84,'id_category'=>171,'name'=>'SUB-D 9-polig Buchse','instock'=>7,'mininstock'=>0,'comment'=>'','id_footprint'=>8,'id_storeloc'=>25,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>85,'id_category'=>171,'name'=>'SUB-D 9-polig Stecker','instock'=>30,'mininstock'=>0,'comment'=>'','id_footprint'=>8,'id_storeloc'=>25,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>86,'id_category'=>171,'name'=>'SUB-D 25-polig Stecker','instock'=>5,'mininstock'=>0,'comment'=>'','id_footprint'=>8,'id_storeloc'=>26,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>87,'id_category'=>171,'name'=>'SUB-D 25-polig Buchse','instock'=>23,'mininstock'=>0,'comment'=>'','id_footprint'=>8,'id_storeloc'=>42,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>88,'id_category'=>171,'name'=>'SUB-D 25-polig Buchse Print,gewingelt','instock'=>4,'mininstock'=>0,'comment'=>'','id_footprint'=>8,'id_storeloc'=>26,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>89,'id_category'=>171,'name'=>'SUB-D 25-polig Stecker Print,gewingelt','instock'=>1,'mininstock'=>0,'comment'=>'','id_footprint'=>8,'id_storeloc'=>26,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>90,'id_category'=>171,'name'=>'SUB-D 9-polig Stecker Print,gewingelt','instock'=>1,'mininstock'=>0,'comment'=>'','id_footprint'=>8,'id_storeloc'=>26,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>91,'id_category'=>190,'name'=>'Bananenbuchse 4mm rot','instock'=>23,'mininstock'=>0,'comment'=>'','id_footprint'=>8,'id_storeloc'=>27,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>92,'id_category'=>190,'name'=>'Bananenbuchse 4mm schwarz','instock'=>35,'mininstock'=>0,'comment'=>'','id_footprint'=>8,'id_storeloc'=>27,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>93,'id_category'=>138,'name'=>'1000µF 10V','instock'=>5,'mininstock'=>0,'comment'=>'neu','id_footprint'=>5,'id_storeloc'=>14,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>94,'id_category'=>138,'name'=>'560µF 25V','instock'=>5,'mininstock'=>0,'comment'=>'neu','id_footprint'=>5,'id_storeloc'=>14,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>95,'id_category'=>138,'name'=>'1000µF 16V','instock'=>13,'mininstock'=>0,'comment'=>'neu, Rubycon','id_footprint'=>5,'id_storeloc'=>14,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>96,'id_category'=>140,'name'=>'1,5µF 35V axial','instock'=>5,'mininstock'=>0,'comment'=>'neu','id_footprint'=>8,'id_storeloc'=>14,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>97,'id_category'=>140,'name'=>'4,7µF 100V axial','instock'=>9,'mininstock'=>0,'comment'=>'neu','id_footprint'=>8,'id_storeloc'=>14,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>98,'id_category'=>142,'name'=>'680nF 400V MKC1866','instock'=>2,'mininstock'=>0,'comment'=>'neu, ERO','id_footprint'=>8,'id_storeloc'=>15,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>99,'id_category'=>145,'name'=>'250nF 400V ','instock'=>3,'mininstock'=>0,'comment'=>'neu, ERO','id_footprint'=>8,'id_storeloc'=>15,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>100,'id_category'=>142,'name'=>'100nF 250V MKC','instock'=>3,'mininstock'=>0,'comment'=>'neu, Siemens','id_footprint'=>8,'id_storeloc'=>15,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>101,'id_category'=>145,'name'=>'33nF 400V','instock'=>15,'mininstock'=>0,'comment'=>'neu, ERO','id_footprint'=>8,'id_storeloc'=>15,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>102,'id_category'=>145,'name'=>'100nF 275V','instock'=>5,'mininstock'=>0,'comment'=>'neu','id_footprint'=>8,'id_storeloc'=>15,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>103,'id_category'=>145,'name'=>'150nF 250V','instock'=>11,'mininstock'=>0,'comment'=>'neu','id_footprint'=>8,'id_storeloc'=>15,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>104,'id_category'=>141,'name'=>'10nF 250V MKT','instock'=>14,'mininstock'=>0,'comment'=>'neu, ERO','id_footprint'=>7,'id_storeloc'=>15,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>105,'id_category'=>141,'name'=>'2,2µF 250V MKT axial','instock'=>2,'mininstock'=>0,'comment'=>'neu','id_footprint'=>8,'id_storeloc'=>15,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>106,'id_category'=>138,'name'=>'220µF 35V','instock'=>8,'mininstock'=>0,'comment'=>'neu, Rubycon','id_footprint'=>5,'id_storeloc'=>15,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>107,'id_category'=>138,'name'=>'47µF 50V radial','instock'=>3,'mininstock'=>0,'comment'=>'neu, SME','id_footprint'=>4,'id_storeloc'=>15,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>108,'id_category'=>145,'name'=>'56nF 1000V','instock'=>4,'mininstock'=>0,'comment'=>'neu, ERO','id_footprint'=>8,'id_storeloc'=>16,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>109,'id_category'=>141,'name'=>'680nF 250V MKT','instock'=>5,'mininstock'=>0,'comment'=>'neu, ERO','id_footprint'=>8,'id_storeloc'=>16,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>110,'id_category'=>141,'name'=>'10nF 1000V MKT axial','instock'=>4,'mininstock'=>0,'comment'=>'neu, ERO','id_footprint'=>8,'id_storeloc'=>16,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>111,'id_category'=>138,'name'=>'47µF 25V axial Philips Typ 021','instock'=>14,'mininstock'=>0,'comment'=>'neu, Philips','id_footprint'=>8,'id_storeloc'=>16,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>112,'id_category'=>138,'name'=>'22µF 50V ','instock'=>57,'mininstock'=>0,'comment'=>'neu, Frolyt','id_footprint'=>4,'id_storeloc'=>16,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>113,'id_category'=>138,'name'=>'10µF 25V axial','instock'=>2,'mininstock'=>0,'comment'=>'neu, Cosonic','id_footprint'=>8,'id_storeloc'=>17,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>114,'id_category'=>186,'name'=>'MA7812','instock'=>2,'mininstock'=>0,'comment'=>'neu, Tesla','id_footprint'=>11,'id_storeloc'=>17,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>115,'id_category'=>106,'name'=>'BUV21','instock'=>2,'mininstock'=>0,'comment'=>'SGS-Thomson Microelectonics','id_footprint'=>11,'id_storeloc'=>17,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>116,'id_category'=>113,'name'=>'BYX55/600','instock'=>5,'mininstock'=>0,'comment'=>'Schnelle Silizium Gleichrichter 2A 350 / 600 V','id_footprint'=>8,'id_storeloc'=>17,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>117,'id_category'=>112,'name'=>'D6-800-KL01','instock'=>2,'mininstock'=>0,'comment'=>' T-4/VE=10 800V D6-800-KL01/AEG','id_footprint'=>8,'id_storeloc'=>17,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>118,'id_category'=>185,'name'=>'UA741CP','instock'=>6,'mininstock'=>0,'comment'=>'','id_footprint'=>12,'id_storeloc'=>60,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>119,'id_category'=>181,'name'=>'SAB0600','instock'=>3,'mininstock'=>0,'comment'=>'Siemens','id_footprint'=>12,'id_storeloc'=>60,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>120,'id_category'=>181,'name'=>'NE555','instock'=>7,'mininstock'=>0,'comment'=>'','id_footprint'=>12,'id_storeloc'=>60,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>121,'id_category'=>181,'name'=>'LM386N','instock'=>4,'mininstock'=>0,'comment'=>'','id_footprint'=>12,'id_storeloc'=>60,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>122,'id_category'=>185,'name'=>'LM324N','instock'=>21,'mininstock'=>0,'comment'=>'','id_footprint'=>13,'id_storeloc'=>60,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>123,'id_category'=>181,'name'=>'HCF4052BE','instock'=>4,'mininstock'=>0,'comment'=>'','id_footprint'=>14,'id_storeloc'=>60,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>124,'id_category'=>184,'name'=>'HCF4071BE','instock'=>2,'mininstock'=>0,'comment'=>'','id_footprint'=>13,'id_storeloc'=>60,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>125,'id_category'=>184,'name'=>'HCF4510BE','instock'=>11,'mininstock'=>0,'comment'=>'','id_footprint'=>14,'id_storeloc'=>60,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>126,'id_category'=>184,'name'=>'TC4093BP','instock'=>2,'mininstock'=>0,'comment'=>'','id_footprint'=>13,'id_storeloc'=>60,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>127,'id_category'=>184,'name'=>'TC4013BP','instock'=>5,'mininstock'=>0,'comment'=>'','id_footprint'=>13,'id_storeloc'=>60,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>128,'id_category'=>183,'name'=>'SN74ALS580AN','instock'=>2,'mininstock'=>0,'comment'=>'','id_footprint'=>16,'id_storeloc'=>61,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>129,'id_category'=>181,'name'=>'TDA4718A','instock'=>2,'mininstock'=>0,'comment'=>'','id_footprint'=>15,'id_storeloc'=>61,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>130,'id_category'=>181,'name'=>'TL497','instock'=>11,'mininstock'=>0,'comment'=>'','id_footprint'=>13,'id_storeloc'=>61,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>131,'id_category'=>181,'name'=>'TL494','instock'=>5,'mininstock'=>0,'comment'=>'','id_footprint'=>14,'id_storeloc'=>60,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>132,'id_category'=>181,'name'=>'SG3525A','instock'=>10,'mininstock'=>0,'comment'=>'','id_footprint'=>14,'id_storeloc'=>61,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>133,'id_category'=>181,'name'=>'LM3524N','instock'=>7,'mininstock'=>0,'comment'=>'','id_footprint'=>14,'id_storeloc'=>61,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>134,'id_category'=>179,'name'=>'HYB511000A-70','instock'=>15,'mininstock'=>0,'comment'=>'','id_footprint'=>15,'id_storeloc'=>61,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>135,'id_category'=>181,'name'=>'CA3524E','instock'=>4,'mininstock'=>0,'comment'=>'','id_footprint'=>14,'id_storeloc'=>61,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>136,'id_category'=>183,'name'=>'SN74S182N','instock'=>1,'mininstock'=>0,'comment'=>'','id_footprint'=>14,'id_storeloc'=>61,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>137,'id_category'=>181,'name'=>'LM723','instock'=>1,'mininstock'=>0,'comment'=>'','id_footprint'=>13,'id_storeloc'=>61,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>138,'id_category'=>107,'name'=>'BC307','instock'=>1,'mininstock'=>0,'comment'=>'','id_footprint'=>19,'id_storeloc'=>62,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>139,'id_category'=>106,'name'=>'BC238B','instock'=>7,'mininstock'=>0,'comment'=>'','id_footprint'=>3,'id_storeloc'=>62,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>140,'id_category'=>106,'name'=>'BCY59','instock'=>6,'mininstock'=>0,'comment'=>'','id_footprint'=>20,'id_storeloc'=>62,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>141,'id_category'=>107,'name'=>'BCY79','instock'=>2,'mininstock'=>0,'comment'=>'','id_footprint'=>20,'id_storeloc'=>62,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>142,'id_category'=>107,'name'=>'2N4033','instock'=>2,'mininstock'=>0,'comment'=>'','id_footprint'=>19,'id_storeloc'=>62,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>143,'id_category'=>106,'name'=>'BD115','instock'=>3,'mininstock'=>0,'comment'=>'','id_footprint'=>19,'id_storeloc'=>62,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>144,'id_category'=>106,'name'=>'BD187','instock'=>4,'mininstock'=>0,'comment'=>'','id_footprint'=>2,'id_storeloc'=>62,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>145,'id_category'=>106,'name'=>'BD135','instock'=>3,'mininstock'=>0,'comment'=>'','id_footprint'=>2,'id_storeloc'=>62,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>146,'id_category'=>106,'name'=>'2N3019','instock'=>13,'mininstock'=>0,'comment'=>'','id_footprint'=>19,'id_storeloc'=>62,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>147,'id_category'=>106,'name'=>'2N2219','instock'=>3,'mininstock'=>0,'comment'=>'','id_footprint'=>19,'id_storeloc'=>62,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>148,'id_category'=>192,'name'=>'Feinsicherung 5*20 125mA ','instock'=>1,'mininstock'=>0,'comment'=>'','id_footprint'=>8,'id_storeloc'=>63,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>149,'id_category'=>192,'name'=>'Feinsicherung 5*20 250mA träge','instock'=>2,'mininstock'=>0,'comment'=>'','id_footprint'=>8,'id_storeloc'=>63,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>150,'id_category'=>192,'name'=>'Feinsicherung 5*20 315mA träge','instock'=>3,'mininstock'=>0,'comment'=>'','id_footprint'=>8,'id_storeloc'=>63,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>151,'id_category'=>192,'name'=>'Feinsicherung 5*20 500mA träge','instock'=>5,'mininstock'=>0,'comment'=>'','id_footprint'=>8,'id_storeloc'=>63,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>152,'id_category'=>192,'name'=>'Feinsicherung 5*20 630mA träge','instock'=>2,'mininstock'=>0,'comment'=>'','id_footprint'=>8,'id_storeloc'=>63,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>153,'id_category'=>192,'name'=>'Feinsicherung 5*20 1,25A träge','instock'=>1,'mininstock'=>0,'comment'=>'','id_footprint'=>8,'id_storeloc'=>63,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>154,'id_category'=>192,'name'=>'Feinsicherung 5*20 1,25A träge','instock'=>1,'mininstock'=>0,'comment'=>'','id_footprint'=>8,'id_storeloc'=>63,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>155,'id_category'=>192,'name'=>'Feinsicherung 5*20 2A träge','instock'=>2,'mininstock'=>0,'comment'=>'','id_footprint'=>8,'id_storeloc'=>63,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>156,'id_category'=>192,'name'=>'Feinsicherung 5*20 2A mittelträge','instock'=>1,'mininstock'=>0,'comment'=>'','id_footprint'=>8,'id_storeloc'=>63,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>157,'id_category'=>192,'name'=>'Feinsicherung 5*20 2,5A mittelträge','instock'=>2,'mininstock'=>0,'comment'=>'','id_footprint'=>8,'id_storeloc'=>63,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>158,'id_category'=>192,'name'=>'Feinsicherung 5*20 2,5A flink','instock'=>1,'mininstock'=>0,'comment'=>'','id_footprint'=>8,'id_storeloc'=>63,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>159,'id_category'=>192,'name'=>'Feinsicherung 5*20 4A träge','instock'=>1,'mininstock'=>0,'comment'=>'','id_footprint'=>8,'id_storeloc'=>63,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>160,'id_category'=>192,'name'=>'Feinsicherung 5*20 4A mittelträge','instock'=>1,'mininstock'=>0,'comment'=>'','id_footprint'=>8,'id_storeloc'=>63,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>161,'id_category'=>192,'name'=>'Feinsicherung 5*20 1,6A flink','instock'=>1,'mininstock'=>0,'comment'=>'','id_footprint'=>8,'id_storeloc'=>63,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>162,'id_category'=>192,'name'=>'Feinsicherung 5*20 400mA träge','instock'=>1,'mininstock'=>0,'comment'=>'','id_footprint'=>8,'id_storeloc'=>64,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>163,'id_category'=>192,'name'=>'Feinsicherung 5*20 10A flink','instock'=>1,'mininstock'=>0,'comment'=>'','id_footprint'=>8,'id_storeloc'=>64,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>164,'id_category'=>192,'name'=>'Feinsicherung 5*20 3,15A träge','instock'=>1,'mininstock'=>0,'comment'=>'','id_footprint'=>8,'id_storeloc'=>64,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>165,'id_category'=>138,'name'=>'2,2µF 100V','instock'=>32,'mininstock'=>0,'comment'=>'neu, THRS','id_footprint'=>4,'id_storeloc'=>64,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>166,'id_category'=>138,'name'=>'22µF 50V ','instock'=>2,'mininstock'=>0,'comment'=>'neu','id_footprint'=>4,'id_storeloc'=>64,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>167,'id_category'=>157,'name'=>'0,33&#937;','instock'=>3,'mininstock'=>0,'comment'=>'','id_footprint'=>8,'id_storeloc'=>64,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>168,'id_category'=>131,'name'=>'68nF','instock'=>2,'mininstock'=>0,'comment'=>'neu','id_footprint'=>4,'id_storeloc'=>64,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>169,'id_category'=>131,'name'=>'330pF','instock'=>62,'mininstock'=>0,'comment'=>'neu','id_footprint'=>4,'id_storeloc'=>64,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>170,'id_category'=>113,'name'=>'1N3900R','instock'=>2,'mininstock'=>0,'comment'=>'','id_footprint'=>8,'id_storeloc'=>64,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>171,'id_category'=>104,'name'=>'MAC212-8','instock'=>2,'mininstock'=>0,'comment'=>'neu, Motorola','id_footprint'=>2,'id_storeloc'=>64,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>172,'id_category'=>107,'name'=>'BD140','instock'=>9,'mininstock'=>0,'comment'=>'','id_footprint'=>2,'id_storeloc'=>65,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>173,'id_category'=>106,'name'=>'BD137','instock'=>23,'mininstock'=>0,'comment'=>'neu','id_footprint'=>2,'id_storeloc'=>65,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>174,'id_category'=>106,'name'=>'BF337','instock'=>3,'mininstock'=>0,'comment'=>'','id_footprint'=>19,'id_storeloc'=>65,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>175,'id_category'=>108,'name'=>'BD680','instock'=>3,'mininstock'=>0,'comment'=>'','id_footprint'=>2,'id_storeloc'=>65,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>176,'id_category'=>106,'name'=>'BC141','instock'=>5,'mininstock'=>0,'comment'=>'','id_footprint'=>19,'id_storeloc'=>65,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>177,'id_category'=>107,'name'=>'BC161','instock'=>8,'mininstock'=>0,'comment'=>'','id_footprint'=>19,'id_storeloc'=>65,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>178,'id_category'=>186,'name'=>'MC7818','instock'=>1,'mininstock'=>0,'comment'=>'neu, Motorola','id_footprint'=>2,'id_storeloc'=>65,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>179,'id_category'=>106,'name'=>'BD249','instock'=>2,'mininstock'=>0,'comment'=>'','id_footprint'=>2,'id_storeloc'=>65,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>180,'id_category'=>107,'name'=>'BD250','instock'=>2,'mininstock'=>0,'comment'=>'','id_footprint'=>2,'id_storeloc'=>65,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>181,'id_category'=>107,'name'=>'BD246','instock'=>5,'mininstock'=>0,'comment'=>'','id_footprint'=>2,'id_storeloc'=>65,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>182,'id_category'=>106,'name'=>'2SD560','instock'=>3,'mininstock'=>0,'comment'=>'','id_footprint'=>2,'id_storeloc'=>66,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>183,'id_category'=>106,'name'=>'2SD986','instock'=>4,'mininstock'=>0,'comment'=>'','id_footprint'=>2,'id_storeloc'=>66,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>184,'id_category'=>108,'name'=>'2SB601','instock'=>2,'mininstock'=>0,'comment'=>'','id_footprint'=>2,'id_storeloc'=>66,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>185,'id_category'=>107,'name'=>'2SB772','instock'=>3,'mininstock'=>0,'comment'=>'','id_footprint'=>21,'id_storeloc'=>66,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>186,'id_category'=>107,'name'=>'2SB744','instock'=>2,'mininstock'=>0,'comment'=>'','id_footprint'=>21,'id_storeloc'=>66,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>187,'id_category'=>107,'name'=>'BD244','instock'=>2,'mininstock'=>0,'comment'=>'','id_footprint'=>2,'id_storeloc'=>66,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>188,'id_category'=>106,'name'=>'2SD882','instock'=>2,'mininstock'=>0,'comment'=>'','id_footprint'=>21,'id_storeloc'=>66,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>189,'id_category'=>106,'name'=>'BD243','instock'=>2,'mininstock'=>0,'comment'=>'','id_footprint'=>2,'id_storeloc'=>66,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>190,'id_category'=>106,'name'=>'2N2219','instock'=>3,'mininstock'=>0,'comment'=>'','id_footprint'=>19,'id_storeloc'=>66,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>191,'id_category'=>102,'name'=>'TIC126','instock'=>5,'mininstock'=>0,'comment'=>'','id_footprint'=>2,'id_storeloc'=>66,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>192,'id_category'=>106,'name'=>'BD587','instock'=>2,'mininstock'=>0,'comment'=>'neu, TFK','id_footprint'=>2,'id_storeloc'=>67,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>193,'id_category'=>186,'name'=>'LM317','instock'=>2,'mininstock'=>0,'comment'=>'','id_footprint'=>2,'id_storeloc'=>67,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>194,'id_category'=>102,'name'=>'BST C1040','instock'=>4,'mininstock'=>0,'comment'=>'','id_footprint'=>2,'id_storeloc'=>67,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>195,'id_category'=>115,'name'=>'mbr2045CT','instock'=>2,'mininstock'=>0,'comment'=>'','id_footprint'=>2,'id_storeloc'=>67,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>196,'id_category'=>106,'name'=>'BF881','instock'=>3,'mininstock'=>0,'comment'=>'','id_footprint'=>2,'id_storeloc'=>67,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>197,'id_category'=>107,'name'=>'BSV15','instock'=>6,'mininstock'=>0,'comment'=>'','id_footprint'=>19,'id_storeloc'=>67,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>198,'id_category'=>106,'name'=>'BSX45','instock'=>3,'mininstock'=>0,'comment'=>'','id_footprint'=>19,'id_storeloc'=>67,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>199,'id_category'=>106,'name'=>'BF197','instock'=>2,'mininstock'=>0,'comment'=>'','id_footprint'=>8,'id_storeloc'=>67,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>200,'id_category'=>107,'name'=>'2SB370','instock'=>2,'mininstock'=>0,'comment'=>'neu, Hitachi','id_footprint'=>8,'id_storeloc'=>67,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>201,'id_category'=>106,'name'=>'BF196','instock'=>4,'mininstock'=>0,'comment'=>'','id_footprint'=>8,'id_storeloc'=>67,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>202,'id_category'=>106,'name'=>'BC172','instock'=>4,'mininstock'=>0,'comment'=>'','id_footprint'=>3,'id_storeloc'=>68,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>203,'id_category'=>106,'name'=>'BC237','instock'=>5,'mininstock'=>0,'comment'=>'','id_footprint'=>3,'id_storeloc'=>68,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>204,'id_category'=>106,'name'=>'BC170','instock'=>2,'mininstock'=>0,'comment'=>'','id_footprint'=>3,'id_storeloc'=>68,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>205,'id_category'=>106,'name'=>'BC547','instock'=>22,'mininstock'=>0,'comment'=>'','id_footprint'=>3,'id_storeloc'=>68,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>206,'id_category'=>106,'name'=>'BC107','instock'=>25,'mininstock'=>0,'comment'=>'','id_footprint'=>20,'id_storeloc'=>68,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>207,'id_category'=>107,'name'=>'BC252','instock'=>3,'mininstock'=>0,'comment'=>'','id_footprint'=>3,'id_storeloc'=>68,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>208,'id_category'=>107,'name'=>'BC558','instock'=>3,'mininstock'=>0,'comment'=>'','id_footprint'=>3,'id_storeloc'=>68,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>209,'id_category'=>107,'name'=>'BC308','instock'=>2,'mininstock'=>0,'comment'=>'','id_footprint'=>3,'id_storeloc'=>68,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>210,'id_category'=>106,'name'=>'BC207','instock'=>10,'mininstock'=>0,'comment'=>'','id_footprint'=>8,'id_storeloc'=>68,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>211,'id_category'=>107,'name'=>'BF179','instock'=>21,'mininstock'=>0,'comment'=>'','id_footprint'=>19,'id_storeloc'=>68,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>212,'id_category'=>194,'name'=>'Signallampe rot 230V 10mm mit Kabel','instock'=>10,'mininstock'=>0,'comment'=>'neu','id_footprint'=>8,'id_storeloc'=>43,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>213,'id_category'=>150,'name'=>'Potiknopf mit Makierung grau/rot für 6mm Achse','instock'=>23,'mininstock'=>0,'comment'=>'neu','id_footprint'=>8,'id_storeloc'=>44,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>214,'id_category'=>132,'name'=>'220nF 63V','instock'=>51,'mininstock'=>0,'comment'=>'neu','id_footprint'=>7,'id_storeloc'=>45,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>215,'id_category'=>131,'name'=>'22pF ?','instock'=>25,'mininstock'=>0,'comment'=>'neu, PRÜFEN des Wertes!','id_footprint'=>5,'id_storeloc'=>28,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>216,'id_category'=>166,'name'=>'3/2-5,08 Printklemme 2-polig','instock'=>33,'mininstock'=>0,'comment'=>'neu, Phönix','id_footprint'=>5,'id_storeloc'=>29,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>217,'id_category'=>138,'name'=>'30000µF 25V','instock'=>2,'mininstock'=>0,'comment'=>'incl. Halter und Schrauben','id_footprint'=>8,'id_storeloc'=>101,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>218,'id_category'=>138,'name'=>'50000µF 50V','instock'=>2,'mininstock'=>0,'comment'=>'','id_footprint'=>8,'id_storeloc'=>101,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>219,'id_category'=>138,'name'=>'50000µF 15V','instock'=>1,'mininstock'=>0,'comment'=>'incl. Schrauben','id_footprint'=>8,'id_storeloc'=>101,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>220,'id_category'=>138,'name'=>'26000µF 25V','instock'=>2,'mininstock'=>1,'comment'=>'','id_footprint'=>8,'id_storeloc'=>101,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>221,'id_category'=>138,'name'=>'60000µF 15V','instock'=>1,'mininstock'=>0,'comment'=>'','id_footprint'=>8,'id_storeloc'=>101,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>222,'id_category'=>138,'name'=>'5000µF 70V','instock'=>1,'mininstock'=>0,'comment'=>'','id_footprint'=>8,'id_storeloc'=>101,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>223,'id_category'=>118,'name'=>'BETR.KONDENSATOR MFB MP 4/402 4µF 400V','instock'=>1,'mininstock'=>0,'comment'=>'','id_footprint'=>8,'id_storeloc'=>101,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>224,'id_category'=>160,'name'=>'Leistungsschalter 3Phasen 380V 20A','instock'=>1,'mininstock'=>0,'comment'=>'Neu, Tip 4G 16-10-U','id_footprint'=>8,'id_storeloc'=>101,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>225,'id_category'=>126,'name'=>'2*210µH 2*10A/500V','instock'=>1,'mininstock'=>0,'comment'=>'','id_footprint'=>8,'id_storeloc'=>101,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>226,'id_category'=>46,'name'=>'DC-DC Converter 36-63/22V/250mA Printmontage','instock'=>1,'mininstock'=>0,'comment'=>'','id_footprint'=>8,'id_storeloc'=>101,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>227,'id_category'=>102,'name'=>'2N686 incl. Kühlkörper','instock'=>2,'mininstock'=>0,'comment'=>'','id_footprint'=>8,'id_storeloc'=>101,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>228,'id_category'=>113,'name'=>'SSIE0820 incl Kühlkörper','instock'=>3,'mininstock'=>0,'comment'=>'','id_footprint'=>8,'id_storeloc'=>101,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>229,'id_category'=>138,'name'=>'20000µF 16V','instock'=>1,'mininstock'=>0,'comment'=>'','id_footprint'=>8,'id_storeloc'=>101,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>230,'id_category'=>138,'name'=>'4700µF 63V','instock'=>1,'mininstock'=>0,'comment'=>'','id_footprint'=>8,'id_storeloc'=>101,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>231,'id_category'=>150,'name'=>'Poti mix','instock'=>6,'mininstock'=>0,'comment'=>'gebraucht','id_footprint'=>8,'id_storeloc'=>45,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>232,'id_category'=>46,'name'=>'Regelverstärker TVR04 Kathrein 10\"','instock'=>1,'mininstock'=>0,'comment'=>'neu','id_footprint'=>8,'id_storeloc'=>111,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>233,'id_category'=>112,'name'=>'1A Diode ^ 1N4148','instock'=>528,'mininstock'=>0,'comment'=>'neu','id_footprint'=>8,'id_storeloc'=>69,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>234,'id_category'=>47,'name'=>'Klebesockel für Kabelbinder 25*25mm','instock'=>79,'mininstock'=>0,'comment'=>'neu','id_footprint'=>8,'id_storeloc'=>111,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>235,'id_category'=>112,'name'=>'BAW76','instock'=>5000,'mininstock'=>0,'comment'=>'neu, Telefunken, ca. Stückzahl','id_footprint'=>8,'id_storeloc'=>121,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>236,'id_category'=>71,'name'=>'Flachbandleitung AWG28 20-polig in cm','instock'=>200,'mininstock'=>0,'comment'=>'neu','id_footprint'=>8,'id_storeloc'=>101,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>237,'id_category'=>178,'name'=>'27256 mix','instock'=>14,'mininstock'=>0,'comment'=>'','id_footprint'=>23,'id_storeloc'=>70,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>238,'id_category'=>178,'name'=>2764,'instock'=>11,'mininstock'=>0,'comment'=>'','id_footprint'=>23,'id_storeloc'=>70,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>239,'id_category'=>179,'name'=>'KM62256BLG-10 SMD','instock'=>4,'mininstock'=>0,'comment'=>'neu, Samsung','id_footprint'=>24,'id_storeloc'=>71,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>240,'id_category'=>179,'name'=>'D43256agu-10LL SMD','instock'=>10,'mininstock'=>0,'comment'=>'neu, NEC','id_footprint'=>24,'id_storeloc'=>71,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>241,'id_category'=>179,'name'=>'MB84256A-10L','instock'=>6,'mininstock'=>0,'comment'=>'neu, Fujitsu','id_footprint'=>24,'id_storeloc'=>71,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>242,'id_category'=>183,'name'=>'DM74ALS244AWM SMD','instock'=>11,'mininstock'=>0,'comment'=>'neu','id_footprint'=>25,'id_storeloc'=>71,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>243,'id_category'=>184,'name'=>'FZL4146G','instock'=>16,'mininstock'=>0,'comment'=>'neu, Siemens','id_footprint'=>26,'id_storeloc'=>71,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>244,'id_category'=>183,'name'=>'DM74ALS573BWM SMD','instock'=>6,'mininstock'=>0,'comment'=>'neu','id_footprint'=>25,'id_storeloc'=>71,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>245,'id_category'=>183,'name'=>'DM74ALS273WM SMD','instock'=>5,'mininstock'=>0,'comment'=>'neu','id_footprint'=>25,'id_storeloc'=>71,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>246,'id_category'=>183,'name'=>'PC74HC373T SMD','instock'=>4,'mininstock'=>0,'comment'=>'neu, Philips','id_footprint'=>25,'id_storeloc'=>71,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>247,'id_category'=>183,'name'=>'SN74ALS574B SMD','instock'=>10,'mininstock'=>0,'comment'=>'neu, TI','id_footprint'=>25,'id_storeloc'=>71,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>248,'id_category'=>183,'name'=>'SN74HCT245 SMD','instock'=>6,'mininstock'=>0,'comment'=>'neu, TI','id_footprint'=>25,'id_storeloc'=>71,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>249,'id_category'=>183,'name'=>'PC74HC139T SMD','instock'=>8,'mininstock'=>0,'comment'=>'neu, Philips','id_footprint'=>27,'id_storeloc'=>72,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>250,'id_category'=>183,'name'=>'PC74HC123T SMD','instock'=>3,'mininstock'=>0,'comment'=>'neu, Philips','id_footprint'=>27,'id_storeloc'=>72,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>251,'id_category'=>183,'name'=>'PC74HC30T SMD','instock'=>6,'mininstock'=>0,'comment'=>'neu, Philips','id_footprint'=>27,'id_storeloc'=>72,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>252,'id_category'=>183,'name'=>'PC74HC175T SMD','instock'=>6,'mininstock'=>0,'comment'=>'neu, Philips','id_footprint'=>27,'id_storeloc'=>72,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>253,'id_category'=>183,'name'=>'DM74LS22M SMD','instock'=>6,'mininstock'=>0,'comment'=>'neu','id_footprint'=>27,'id_storeloc'=>72,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>254,'id_category'=>184,'name'=>'HC4050 SMD','instock'=>7,'mininstock'=>0,'comment'=>'neu, Motorola','id_footprint'=>27,'id_storeloc'=>72,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>255,'id_category'=>184,'name'=>'HC595A SMD','instock'=>6,'mininstock'=>0,'comment'=>'neu, Motorola','id_footprint'=>27,'id_storeloc'=>72,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>256,'id_category'=>184,'name'=>'MC14014B SMD','instock'=>3,'mininstock'=>0,'comment'=>'neu, Motorola','id_footprint'=>27,'id_storeloc'=>72,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>257,'id_category'=>183,'name'=>'74F194D SMD','instock'=>11,'mininstock'=>0,'comment'=>'neu, Signetics','id_footprint'=>27,'id_storeloc'=>72,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>258,'id_category'=>183,'name'=>'74F74D SMD','instock'=>3,'mininstock'=>0,'comment'=>'neu, Signetics','id_footprint'=>27,'id_storeloc'=>72,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>259,'id_category'=>190,'name'=>'Bananenbuchse 4mm hellrot','instock'=>7,'mininstock'=>0,'comment'=>'','id_footprint'=>8,'id_storeloc'=>73,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>260,'id_category'=>190,'name'=>'Bananenbuchse 4mm gelb','instock'=>8,'mininstock'=>0,'comment'=>'','id_footprint'=>8,'id_storeloc'=>73,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>261,'id_category'=>190,'name'=>'Bananenbuchse 4mm blau','instock'=>9,'mininstock'=>0,'comment'=>'','id_footprint'=>8,'id_storeloc'=>73,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>262,'id_category'=>190,'name'=>'Polklemme 4mm rot','instock'=>1,'mininstock'=>0,'comment'=>'Hirschmann','id_footprint'=>8,'id_storeloc'=>73,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>263,'id_category'=>100,'name'=>'B0580 geb.','instock'=>7,'mininstock'=>0,'comment'=>'Siemens','id_footprint'=>6,'id_storeloc'=>73,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>264,'id_category'=>100,'name'=>'B0540','instock'=>5,'mininstock'=>0,'comment'=>'Siemens','id_footprint'=>6,'id_storeloc'=>73,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>265,'id_category'=>100,'name'=>'C1740','instock'=>2,'mininstock'=>0,'comment'=>'Siemens','id_footprint'=>6,'id_storeloc'=>73,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>266,'id_category'=>106,'name'=>'BF258','instock'=>7,'mininstock'=>0,'comment'=>'neu','id_footprint'=>19,'id_storeloc'=>73,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>267,'id_category'=>107,'name'=>'BC160','instock'=>2,'mininstock'=>0,'comment'=>'','id_footprint'=>19,'id_storeloc'=>73,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>268,'id_category'=>167,'name'=>'Lötösen M3','instock'=>98,'mininstock'=>0,'comment'=>'neu','id_footprint'=>8,'id_storeloc'=>73,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>269,'id_category'=>98,'name'=>'7-Segment-Anzeige mix','instock'=>6,'mininstock'=>0,'comment'=>'','id_footprint'=>8,'id_storeloc'=>74,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>270,'id_category'=>98,'name'=>'HD2121G 7-Segment-Anzeige 2 Digit','instock'=>1,'mininstock'=>0,'comment'=>'neu','id_footprint'=>8,'id_storeloc'=>74,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>271,'id_category'=>94,'name'=>'Flächen LED rot 5*3mm','instock'=>16,'mininstock'=>0,'comment'=>'','id_footprint'=>4,'id_storeloc'=>74,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>272,'id_category'=>94,'name'=>'LED 5mm mit Kunststoffsockel 90 Grad grün','instock'=>2,'mininstock'=>0,'comment'=>'','id_footprint'=>4,'id_storeloc'=>74,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>273,'id_category'=>94,'name'=>'LED 5mm mit Kunststoffsockel 90 Grad rot','instock'=>12,'mininstock'=>0,'comment'=>'','id_footprint'=>4,'id_storeloc'=>74,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>274,'id_category'=>183,'name'=>'DM74LS136M SMD','instock'=>3,'mininstock'=>0,'comment'=>'neu','id_footprint'=>27,'id_storeloc'=>74,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>275,'id_category'=>183,'name'=>'MM74HC00 SMD','instock'=>4,'mininstock'=>0,'comment'=>'neu','id_footprint'=>27,'id_storeloc'=>74,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>276,'id_category'=>183,'name'=>'LS279A SMD','instock'=>3,'mininstock'=>0,'comment'=>'neu, TI','id_footprint'=>27,'id_storeloc'=>74,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>277,'id_category'=>183,'name'=>'ALS32 SMD','instock'=>6,'mininstock'=>0,'comment'=>'neu, TI','id_footprint'=>28,'id_storeloc'=>74,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>278,'id_category'=>183,'name'=>'ALS38A SMD','instock'=>2,'mininstock'=>0,'comment'=>'neu, TI','id_footprint'=>28,'id_storeloc'=>74,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>279,'id_category'=>151,'name'=>'Trimmer, liegend, 470 Ohm','instock'=>4,'mininstock'=>0,'comment'=>'neu','id_footprint'=>8,'id_storeloc'=>75,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>280,'id_category'=>151,'name'=>'Trimmer, stehend, 500 Ohm','instock'=>1,'mininstock'=>0,'comment'=>'','id_footprint'=>8,'id_storeloc'=>75,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>281,'id_category'=>151,'name'=>'Trimmer, stehend, 220 Ohm','instock'=>4,'mininstock'=>0,'comment'=>'','id_footprint'=>8,'id_storeloc'=>75,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>282,'id_category'=>151,'name'=>'Trimmer, stehend, 470 Ohm','instock'=>1,'mininstock'=>0,'comment'=>'','id_footprint'=>8,'id_storeloc'=>75,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>283,'id_category'=>151,'name'=>'Trimmer, liegend, 150 Ohm','instock'=>1,'mininstock'=>0,'comment'=>'','id_footprint'=>8,'id_storeloc'=>75,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>284,'id_category'=>151,'name'=>'Trimmer, liegend, 100 Ohm','instock'=>3,'mininstock'=>0,'comment'=>'','id_footprint'=>8,'id_storeloc'=>75,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>285,'id_category'=>151,'name'=>'Trimmer, stehend, 100 Ohm','instock'=>1,'mininstock'=>0,'comment'=>'','id_footprint'=>8,'id_storeloc'=>75,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>286,'id_category'=>151,'name'=>'Trimmer, liegend, 1 M-Ohm','instock'=>1,'mininstock'=>0,'comment'=>'','id_footprint'=>8,'id_storeloc'=>75,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>287,'id_category'=>151,'name'=>'Trimmer, stehend, 1 M-Ohm','instock'=>3,'mininstock'=>0,'comment'=>'','id_footprint'=>8,'id_storeloc'=>75,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>288,'id_category'=>151,'name'=>'Trimmer, liegend, 2 M-Ohm','instock'=>1,'mininstock'=>0,'comment'=>'','id_footprint'=>8,'id_storeloc'=>75,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>289,'id_category'=>151,'name'=>'Trimmer, liegend, 2,2 M-Ohm','instock'=>5,'mininstock'=>0,'comment'=>'','id_footprint'=>8,'id_storeloc'=>75,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>290,'id_category'=>151,'name'=>'Trimmer, liegend, 4 M-Ohm','instock'=>1,'mininstock'=>0,'comment'=>'','id_footprint'=>8,'id_storeloc'=>75,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>291,'id_category'=>151,'name'=>'Trimmer, liegend, 4,7 M-Ohm','instock'=>2,'mininstock'=>0,'comment'=>'','id_footprint'=>8,'id_storeloc'=>75,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>292,'id_category'=>151,'name'=>'Trimmer, stehend, 4,7 M-Ohm','instock'=>2,'mininstock'=>0,'comment'=>'','id_footprint'=>8,'id_storeloc'=>75,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>293,'id_category'=>151,'name'=>'Trimmer, liegend, 1 K-Ohm','instock'=>1,'mininstock'=>0,'comment'=>'','id_footprint'=>8,'id_storeloc'=>75,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>294,'id_category'=>151,'name'=>'Trimmer, stehend, 1 K-Ohm','instock'=>1,'mininstock'=>0,'comment'=>'','id_footprint'=>8,'id_storeloc'=>75,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>295,'id_category'=>151,'name'=>'Trimmer, liegend, 2,2 K-Ohm','instock'=>4,'mininstock'=>0,'comment'=>'','id_footprint'=>8,'id_storeloc'=>75,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>296,'id_category'=>151,'name'=>'Trimmer, liegend, 2,5 K-Ohm','instock'=>1,'mininstock'=>0,'comment'=>'','id_footprint'=>8,'id_storeloc'=>75,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>297,'id_category'=>151,'name'=>'Trimmer, stehend, 2,2 K-Ohm','instock'=>3,'mininstock'=>0,'comment'=>'','id_footprint'=>8,'id_storeloc'=>75,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>298,'id_category'=>151,'name'=>'Trimmer, stehend, 2,5 K-Ohm','instock'=>2,'mininstock'=>0,'comment'=>'','id_footprint'=>8,'id_storeloc'=>75,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>299,'id_category'=>151,'name'=>'Trimmer, stehend, 4,7 K-Ohm','instock'=>10,'mininstock'=>0,'comment'=>'','id_footprint'=>8,'id_storeloc'=>76,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>300,'id_category'=>151,'name'=>'Trimmer, stehend, 5 K-Ohm','instock'=>4,'mininstock'=>0,'comment'=>'','id_footprint'=>8,'id_storeloc'=>76,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>301,'id_category'=>151,'name'=>'Trimmer, liegend, 4,7 K-Ohm','instock'=>23,'mininstock'=>0,'comment'=>'','id_footprint'=>8,'id_storeloc'=>76,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>302,'id_category'=>151,'name'=>'Trimmer, liegend, 5 K-Ohm','instock'=>1,'mininstock'=>0,'comment'=>'','id_footprint'=>8,'id_storeloc'=>76,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>303,'id_category'=>151,'name'=>'Trimmer, liegend, 10 K-Ohm','instock'=>31,'mininstock'=>0,'comment'=>'','id_footprint'=>8,'id_storeloc'=>77,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>304,'id_category'=>151,'name'=>'Trimmer, stehend, 10 K-Ohm','instock'=>6,'mininstock'=>0,'comment'=>'','id_footprint'=>8,'id_storeloc'=>77,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>305,'id_category'=>151,'name'=>'Trimmer, liegend, 22 K-Ohm','instock'=>15,'mininstock'=>0,'comment'=>'','id_footprint'=>8,'id_storeloc'=>76,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>306,'id_category'=>151,'name'=>'Trimmer, stehend, 22 K-Ohm','instock'=>9,'mininstock'=>0,'comment'=>'','id_footprint'=>8,'id_storeloc'=>76,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>307,'id_category'=>151,'name'=>'Trimmer, liegend, 47 K-Ohm','instock'=>10,'mininstock'=>0,'comment'=>'','id_footprint'=>8,'id_storeloc'=>76,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>308,'id_category'=>151,'name'=>'Trimmer, liegend, 50 K-Ohm','instock'=>1,'mininstock'=>0,'comment'=>'','id_footprint'=>8,'id_storeloc'=>76,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>309,'id_category'=>151,'name'=>'Trimmer, stehend, 47 K-Ohm','instock'=>4,'mininstock'=>0,'comment'=>'','id_footprint'=>8,'id_storeloc'=>76,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>310,'id_category'=>151,'name'=>'Trimmer, stehend, 50 K-Ohm','instock'=>5,'mininstock'=>0,'comment'=>'','id_footprint'=>8,'id_storeloc'=>76,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>311,'id_category'=>151,'name'=>'Trimmer, liegend, 100 K-Ohm','instock'=>30,'mininstock'=>0,'comment'=>'','id_footprint'=>8,'id_storeloc'=>76,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>312,'id_category'=>151,'name'=>'Trimmer, liegend, 100 K-Ohm mit Schalter','instock'=>1,'mininstock'=>0,'comment'=>'','id_footprint'=>8,'id_storeloc'=>76,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>313,'id_category'=>151,'name'=>'Trimmer, Lötösen, 100 K-Ohm mit Schalter ','instock'=>1,'mininstock'=>0,'comment'=>'','id_footprint'=>8,'id_storeloc'=>76,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>314,'id_category'=>151,'name'=>'Trimmer, stehend, 100 K-Ohm','instock'=>9,'mininstock'=>0,'comment'=>'','id_footprint'=>8,'id_storeloc'=>76,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>315,'id_category'=>151,'name'=>'Trimmer, liegend, 150 K-Ohm','instock'=>3,'mininstock'=>0,'comment'=>'','id_footprint'=>8,'id_storeloc'=>76,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>316,'id_category'=>151,'name'=>'Trimmer, liegend, 220 K-Ohm','instock'=>14,'mininstock'=>0,'comment'=>'','id_footprint'=>8,'id_storeloc'=>76,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>317,'id_category'=>151,'name'=>'Trimmer, stehend, 220 K-Ohm','instock'=>9,'mininstock'=>0,'comment'=>'','id_footprint'=>8,'id_storeloc'=>76,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>318,'id_category'=>151,'name'=>'Trimmer, stehend, 250 K-Ohm','instock'=>1,'mininstock'=>0,'comment'=>'','id_footprint'=>8,'id_storeloc'=>76,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>319,'id_category'=>151,'name'=>'Trimmer, liegend, 470 K-Ohm','instock'=>8,'mininstock'=>0,'comment'=>'','id_footprint'=>8,'id_storeloc'=>76,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>320,'id_category'=>151,'name'=>'Trimmer, liegend, 500 K-Ohm','instock'=>3,'mininstock'=>0,'comment'=>'','id_footprint'=>8,'id_storeloc'=>76,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>321,'id_category'=>151,'name'=>'Trimmer, stehend, 470 K-Ohm','instock'=>1,'mininstock'=>0,'comment'=>'','id_footprint'=>8,'id_storeloc'=>76,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>322,'id_category'=>151,'name'=>'Trimmer, stehend, 500 K-Ohm','instock'=>3,'mininstock'=>0,'comment'=>'','id_footprint'=>8,'id_storeloc'=>76,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>323,'id_category'=>183,'name'=>'DM74ALS541WM SMD','instock'=>1,'mininstock'=>0,'comment'=>'neu','id_footprint'=>25,'id_storeloc'=>76,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>324,'id_category'=>183,'name'=>'PC74HC157T SMD','instock'=>1,'mininstock'=>0,'comment'=>'neu, Philips','id_footprint'=>27,'id_storeloc'=>76,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>325,'id_category'=>185,'name'=>'LM319D SMD','instock'=>1,'mininstock'=>0,'comment'=>'neu','id_footprint'=>28,'id_storeloc'=>76,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>326,'id_category'=>179,'name'=>'M5M5256BFP SMD','instock'=>1,'mininstock'=>0,'comment'=>'neu, Mitsubishi Semiconductor','id_footprint'=>24,'id_storeloc'=>76,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>327,'id_category'=>181,'name'=>'ADG508AKR SMD','instock'=>1,'mininstock'=>0,'comment'=>'neu','id_footprint'=>27,'id_storeloc'=>76,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>328,'id_category'=>179,'name'=>'HYB514400AJ-70 SMD','instock'=>2,'mininstock'=>0,'comment'=>'neu, Siemens','id_footprint'=>29,'id_storeloc'=>76,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>329,'id_category'=>179,'name'=>'424400-70','instock'=>1,'mininstock'=>0,'comment'=>'neu, NEC','id_footprint'=>29,'id_storeloc'=>76,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>330,'id_category'=>179,'name'=>'814400A-70 SMD','instock'=>1,'mininstock'=>0,'comment'=>'neu','id_footprint'=>29,'id_storeloc'=>76,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>331,'id_category'=>112,'name'=>'1N3881 incl. Kühlkörper','instock'=>1,'mininstock'=>0,'comment'=>'','id_footprint'=>8,'id_storeloc'=>77,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>332,'id_category'=>102,'name'=>'BST C0326S6 incl. Kühlkörper','instock'=>2,'mininstock'=>0,'comment'=>'','id_footprint'=>8,'id_storeloc'=>77,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>333,'id_category'=>112,'name'=>'BY250','instock'=>1,'mininstock'=>0,'comment'=>'','id_footprint'=>8,'id_storeloc'=>76,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>334,'id_category'=>112,'name'=>'BYW80','instock'=>1,'mininstock'=>0,'comment'=>'','id_footprint'=>8,'id_storeloc'=>76,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>335,'id_category'=>113,'name'=>'BYX55/350','instock'=>1,'mininstock'=>0,'comment'=>'','id_footprint'=>8,'id_storeloc'=>76,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>336,'id_category'=>112,'name'=>'BY188A','instock'=>1,'mininstock'=>0,'comment'=>'','id_footprint'=>8,'id_storeloc'=>76,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>337,'id_category'=>112,'name'=>'MR854','instock'=>1,'mininstock'=>0,'comment'=>'','id_footprint'=>8,'id_storeloc'=>76,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>338,'id_category'=>114,'name'=>'ZPY15','instock'=>1,'mininstock'=>0,'comment'=>'','id_footprint'=>8,'id_storeloc'=>76,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>339,'id_category'=>114,'name'=>'ZD15','instock'=>1,'mininstock'=>0,'comment'=>'','id_footprint'=>8,'id_storeloc'=>76,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>340,'id_category'=>113,'name'=>'BYY36','instock'=>1,'mininstock'=>0,'comment'=>'','id_footprint'=>8,'id_storeloc'=>76,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>341,'id_category'=>100,'name'=>'Dioden mix','instock'=>100,'mininstock'=>0,'comment'=>'','id_footprint'=>8,'id_storeloc'=>77,'id_supplier'=>1,'supplierpartnr'=>''),
  array('id'=>342,'id_category'=>166,'name'=>'3/3-7,62 Printklemme 2-polig','instock'=>45,'mininstock'=>0,'comment'=>'neu, Phönix','id_footprint'=>6,'id_storeloc'=>30,'id_supplier'=>1,'supplierpartnr'=>'')
);
