<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'api_platform.swagger.command.swagger_command' shared service.

return $this->services['api_platform.swagger.command.swagger_command'] = new \ApiPlatform\Core\Bridge\Symfony\Bundle\Command\SwaggerCommand(${($_ = isset($this->services['api_platform.swagger.normalizer.documentation']) ? $this->services['api_platform.swagger.normalizer.documentation'] : $this->getApiPlatform_Swagger_Normalizer_DocumentationService()) && false ?: '_'}, ${($_ = isset($this->services['api_platform.metadata.resource.name_collection_factory']) ? $this->services['api_platform.metadata.resource.name_collection_factory'] : $this->getApiPlatform_Metadata_Resource_NameCollectionFactoryService()) && false ?: '_'}, 'PartKeepr', '', '0.0.1', $this->parameters['api_platform.formats']);
