<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'deprecated.form.registry.csrf' shared service.

@trigger_error('The service "deprecated.form.registry.csrf" is internal and deprecated since Symfony 3.3 and will be removed in Symfony 4.0', E_USER_DEPRECATED);

$this->services['deprecated.form.registry.csrf'] = $instance = new \stdClass();

$instance->registry = [];

return $instance;
