<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'filesystem' shared service.

return $this->services['filesystem'] = new \Symfony\Component\Filesystem\Filesystem();
