<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'filesystem_footprintattachment' shared service.

return $this->services['filesystem_footprintattachment'] = new \Gaufrette\Filesystem(new \Gaufrette\Adapter\Local(($this->targetDirs[3].'/../data/files/FootprintAttachment/'), true));
