<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'fos_rest.routing.loader.yaml_collection' shared service.

@trigger_error('The fos_rest.routing.loader.yaml_collection service is deprecated since FOSRestBundle 2.8. You can disable it by setting the config `fos_rest.routing_loader.enabled` to `false`.', E_USER_DEPRECATED);

return $this->services['fos_rest.routing.loader.yaml_collection'] = new \FOS\RestBundle\Routing\Loader\RestYamlCollectionLoader(${($_ = isset($this->services['file_locator']) ? $this->services['file_locator'] : ($this->services['file_locator'] = new \Symfony\Component\HttpKernel\Config\FileLocator(${($_ = isset($this->services['kernel']) ? $this->services['kernel'] : $this->get('kernel', 1)) && false ?: '_'}, ($this->targetDirs[3].'/Resources'), [0 => $this->targetDirs[3]]))) && false ?: '_'}, ${($_ = isset($this->services['fos_rest.routing.loader.processor']) ? $this->services['fos_rest.routing.loader.processor'] : $this->load('getFosRest_Routing_Loader_ProcessorService.php')) && false ?: '_'}, true, ['json' => false, 'xml' => false], NULL);
