<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'importer_service' shared service.

return $this->services['importer_service'] = new \PartKeepr\ImportBundle\Service\ImporterService(${($_ = isset($this->services['doctrine']) ? $this->services['doctrine'] : $this->getDoctrineService()) && false ?: '_'}, ${($_ = isset($this->services['doctrine_reflection_service']) ? $this->services['doctrine_reflection_service'] : $this->load('getDoctrineReflectionServiceService.php')) && false ?: '_'}, ${($_ = isset($this->services['doctrine_reflection_service.search_filter']) ? $this->services['doctrine_reflection_service.search_filter'] : $this->load('getDoctrineReflectionService_SearchFilterService.php')) && false ?: '_'});
