<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'liip_functional_test.query.counter' shared service.

return $this->services['liip_functional_test.query.counter'] = new \Liip\FunctionalTestBundle\QueryCounter(NULL, ${($_ = isset($this->services['annotation_reader']) ? $this->services['annotation_reader'] : $this->getAnnotationReaderService()) && false ?: '_'});
