<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'nfq.sprite' shared service.

$this->services['nfq.sprite'] = $instance = new \SpriteGenerator\Services\SpriteService();

$instance->setConfig(['fugue16' => ['inDir' => ($this->targetDirs[3].'/../vendor/brainbits/fugue-icons-bundle/src/Brainbits/FugueIconsBundle/Resources/public/icons/fugue/16/'), 'outImage' => ($this->targetDirs[3].'/../web/spritesheets/fugue-16.png'), 'outCss' => ($this->targetDirs[3].'/../web/spritesheets/fugue-16.css'), 'relativeImagePath' => './', 'padding' => 5, 'spriteClass' => 'fugue-icon', 'cssFormat' => 'css', 'imagePositioning' => 'min-image', 'imageGenerator' => 'gd2'], 'partkeepr' => ['inDir' => ($this->targetDirs[3].'/../src/PartKeepr/FrontendBundle/Resources/public/images/icons/'), 'outImage' => ($this->targetDirs[3].'/../web/spritesheets/partkeepr.png'), 'outCss' => ($this->targetDirs[3].'/../web/spritesheets/partkeepr.css'), 'relativeImagePath' => './', 'padding' => 5, 'spriteClass' => 'partkeepr-icon', 'cssFormat' => 'css', 'imagePositioning' => 'min-image', 'imageGenerator' => 'gd2']]);

return $instance;
