<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'partkeepr.part_measurement_unit.set_default' shared service.

return $this->services['partkeepr.part_measurement_unit.set_default'] = new \PartKeepr\PartBundle\Action\SetDefaultUnitAction(${($_ = isset($this->services['partkeepr.part_measurement_unit_service']) ? $this->services['partkeepr.part_measurement_unit_service'] : $this->load('getPartkeepr_PartMeasurementUnitServiceService.php')) && false ?: '_'});
