<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'partkeepr.auth.login' shared service.

return $this->services['partkeepr.auth.login'] = new \PartKeepr\AuthBundle\Action\LoginAction(${($_ = isset($this->services['partkeepr.userservice']) ? $this->services['partkeepr.userservice'] : $this->load('getPartkeepr_UserserviceService.php')) && false ?: '_'}, ${($_ = isset($this->services['partkeepr.user_preference_service']) ? $this->services['partkeepr.user_preference_service'] : $this->load('getPartkeepr_UserPreferenceServiceService.php')) && false ?: '_'});
