<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'partkeepr.part.add_stock' shared service.

return $this->services['partkeepr.part.add_stock'] = new \PartKeepr\PartBundle\Action\AddStockAction(${($_ = isset($this->services['partkeepr.userservice']) ? $this->services['partkeepr.userservice'] : $this->load('getPartkeepr_UserserviceService.php')) && false ?: '_'}, ${($_ = isset($this->services['doctrine']) ? $this->services['doctrine'] : $this->getDoctrineService()) && false ?: '_'});
