<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'partkeepr.exceptionwrapper' shared service.

return $this->services['partkeepr.exceptionwrapper'] = new \PartKeepr\DoctrineReflectionBundle\Exception\ExceptionWrapperHandler();
