<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'partkeepr.user.post' shared service.

return $this->services['partkeepr.user.post'] = new \PartKeepr\AuthBundle\Action\PostUserAction(${($_ = isset($this->services['partkeepr.userservice']) ? $this->services['partkeepr.userservice'] : $this->load('getPartkeepr_UserserviceService.php')) && false ?: '_'});
