<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'partkeepr_image_service' shared service.

return $this->services['partkeepr_image_service'] = new \PartKeepr\ImageBundle\Services\ImageService($this);
