<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'part.category_path_listener' shared service.

return $this->services['part.category_path_listener'] = new \PartKeepr\PartBundle\Listeners\CategoryPathListener($this);
