<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'partkeepr_systemservice' shared service.

return $this->services['partkeepr_systemservice'] = new \PartKeepr\CoreBundle\Services\SystemService(${($_ = isset($this->services['doctrine']) ? $this->services['doctrine'] : $this->getDoctrineService()) && false ?: '_'}, $this, ${($_ = isset($this->services['partkeepr.versionservice']) ? $this->services['partkeepr.versionservice'] : $this->load('getPartkeepr_VersionserviceService.php')) && false ?: '_'}, ${($_ = isset($this->services['partkeepr.cronlogger_service']) ? $this->services['partkeepr.cronlogger_service'] : $this->load('getPartkeepr_CronloggerServiceService.php')) && false ?: '_'});
