<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'partkeepr.remote_file_loader.factory' shared service.

return $this->services['partkeepr.remote_file_loader.factory'] = new \PartKeepr\RemoteFileLoader\RemoteFileLoaderFactory();
