<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'partkeepr.category.get_root_node' shared service.

return $this->services['partkeepr.category.get_root_node'] = new \PartKeepr\CategoryBundle\Action\GetRootNodeAction(${($_ = isset($this->services['doctrine']) ? $this->services['doctrine'] : $this->getDoctrineService()) && false ?: '_'});
