<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'partkeepr.tip_of_the_day.mark_all_unread' shared service.

return $this->services['partkeepr.tip_of_the_day.mark_all_unread'] = new \PartKeepr\TipOfTheDayBundle\Action\MarkTipsAsUnreadAction(${($_ = isset($this->services['doctrine.orm.default_entity_manager']) ? $this->services['doctrine.orm.default_entity_manager'] : $this->load('getDoctrine_Orm_DefaultEntityManagerService.php')) && false ?: '_'}, ${($_ = isset($this->services['partkeepr.userservice']) ? $this->services['partkeepr.userservice'] : $this->load('getPartkeepr_UserserviceService.php')) && false ?: '_'});
