<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'partkeepr.category.move' shared service.

return $this->services['partkeepr.category.move'] = new \PartKeepr\CategoryBundle\Action\MoveAction(${($_ = isset($this->services['doctrine']) ? $this->services['doctrine'] : $this->getDoctrineService()) && false ?: '_'});
