<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Liip\FunctionalTestBundle\Command\RunParatestCommand' shared service.

return $this->services['Liip\\FunctionalTestBundle\\Command\\RunParatestCommand'] = new \Liip\FunctionalTestBundle\Command\RunParatestCommand();
