<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'security.encoder_factory' shared service.

return $this->services['security.encoder_factory'] = new \Symfony\Component\Security\Core\Encoder\EncoderFactory(['Symfony\\Component\\Security\\Core\\User\\User' => ['algorithm' => 'sha512', 'iterations' => 1, 'hash_algorithm' => 'sha512', 'key_length' => 40, 'ignore_case' => false, 'encode_as_base64' => true, 'cost' => 13], 'FOS\\UserBundle\\Model\\UserInterface' => ['algorithm' => 'sha512', 'iterations' => 1, 'hash_algorithm' => 'sha512', 'key_length' => 40, 'ignore_case' => false, 'encode_as_base64' => true, 'cost' => 13], 'PartKeepr\\AuthBundle\\Entity\\User' => ['algorithm' => 'md5', 'iterations' => 1, 'encode_as_base64' => false, 'hash_algorithm' => 'sha512', 'key_length' => 40, 'ignore_case' => false, 'cost' => 13]]);
