<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'assetic.filter.cssrewrite' shared service.

return $this->services['assetic.filter.cssrewrite'] = new \Assetic\Filter\CssRewriteFilter();
