<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'api_platform.listener.view.serialize' shared service.

return $this->services['api_platform.listener.view.serialize'] = new \ApiPlatform\Core\EventListener\SerializeListener(${($_ = isset($this->services['serializer']) ? $this->services['serializer'] : $this->getSerializerService()) && false ?: '_'}, ${($_ = isset($this->services['api_platform.serializer.context_builder']) ? $this->services['api_platform.serializer.context_builder'] : $this->getApiPlatform_Serializer_ContextBuilderService()) && false ?: '_'});
