<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'filesystem_mimetype_icons' shared service.

return $this->services['filesystem_mimetype_icons'] = new \Gaufrette\Filesystem(new \Gaufrette\Adapter\Local(($this->targetDirs[3].'/../src/PartKeepr/MimetypeIconsBundle/Resources/public/images/mimes/'), true));
