<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'partkeepr.tip_of_the_day_history.collection_get' shared service.

return $this->services['partkeepr.tip_of_the_day_history.collection_get'] = new \PartKeepr\TipOfTheDayBundle\Action\GetTipHistoryCollectionAction(${($_ = isset($this->services['partkeepr.userservice']) ? $this->services['partkeepr.userservice'] : $this->load('getPartkeepr_UserserviceService.php')) && false ?: '_'});
