<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'partkeepr.batchjob.execute' shared service.

return $this->services['partkeepr.batchjob.execute'] = new \PartKeepr\BatchJobBundle\Action\ExecuteBatchJobAction(${($_ = isset($this->services['doctrine.orm.default_entity_manager']) ? $this->services['doctrine.orm.default_entity_manager'] : $this->load('getDoctrine_Orm_DefaultEntityManagerService.php')) && false ?: '_'}, ${($_ = isset($this->services['doctrine_reflection_service.search_filter']) ? $this->services['doctrine_reflection_service.search_filter'] : $this->load('getDoctrineReflectionService_SearchFilterService.php')) && false ?: '_'}, ${($_ = isset($this->services['doctrine_reflection_service']) ? $this->services['doctrine_reflection_service'] : $this->load('getDoctrineReflectionServiceService.php')) && false ?: '_'});
