<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'partkeepr.setup.config_service' shared service.

return $this->services['partkeepr.setup.config_service'] = new \PartKeepr\SetupBundle\Services\ConfigSetupService(${($_ = isset($this->services['templating']) ? $this->services['templating'] : $this->load('getTemplatingService.php')) && false ?: '_'});
