<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'partkeepr.setup.footprint_service' shared service.

return $this->services['partkeepr.setup.footprint_service'] = new \PartKeepr\SetupBundle\Services\FootprintSetupService(${($_ = isset($this->services['doctrine.orm.default_entity_manager']) ? $this->services['doctrine.orm.default_entity_manager'] : $this->load('getDoctrine_Orm_DefaultEntityManagerService.php')) && false ?: '_'}, ${($_ = isset($this->services['partkeepr.footprint.category_service']) ? $this->services['partkeepr.footprint.category_service'] : $this->load('getPartkeepr_Footprint_CategoryServiceService.php')) && false ?: '_'}, ${($_ = isset($this->services['partkeepr_uploadedfile_service']) ? $this->services['partkeepr_uploadedfile_service'] : ($this->services['partkeepr_uploadedfile_service'] = new \PartKeepr\UploadedFileBundle\Services\UploadedFileService($this))) && false ?: '_'}, ${($_ = isset($this->services['kernel']) ? $this->services['kernel'] : $this->get('kernel', 1)) && false ?: '_'});
