<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'partkeepr.part.put' shared service.

return $this->services['partkeepr.part.put'] = new \PartKeepr\PartBundle\Action\PartPutAction(${($_ = isset($this->services['partkeepr.part_service']) ? $this->services['partkeepr.part_service'] : $this->load('getPartkeepr_PartServiceService.php')) && false ?: '_'});
