<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'part.stock_level_listener' shared service.

return $this->services['part.stock_level_listener'] = new \PartKeepr\PartBundle\Listeners\StockLevelListener($this);
