<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'partkeepr.parts.collection_get' shared service.

return $this->services['partkeepr.parts.collection_get'] = new \PartKeepr\PartBundle\Action\GetPartsAction(${($_ = isset($this->services['doctrine.orm.default_entity_manager']) ? $this->services['doctrine.orm.default_entity_manager'] : $this->load('getDoctrine_Orm_DefaultEntityManagerService.php')) && false ?: '_'}, ${($_ = isset($this->services['partkeepr.part_service']) ? $this->services['partkeepr.part_service'] : $this->load('getPartkeepr_PartServiceService.php')) && false ?: '_'});
