<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'partkeepr.octopart_service' shared service.

return $this->services['partkeepr.octopart_service'] = new \PartKeepr\OctoPartBundle\Services\OctoPartService('', '3');
