<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'partkeepr.grid_preset.mark_as_default' shared service.

return $this->services['partkeepr.grid_preset.mark_as_default'] = new \PartKeepr\FrontendBundle\Action\MarkAsDefaultAction(${($_ = isset($this->services['partkeepr.gridpresetservice']) ? $this->services['partkeepr.gridpresetservice'] : $this->load('getPartkeepr_GridpresetserviceService.php')) && false ?: '_'});
