<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'partkeepr.system_preference.set_preference' shared service.

return $this->services['partkeepr.system_preference.set_preference'] = new \PartKeepr\SystemPreferenceBundle\Action\SetPreferenceAction(${($_ = isset($this->services['partkeepr.system_preference_service']) ? $this->services['partkeepr.system_preference_service'] : $this->load('getPartkeepr_SystemPreferenceServiceService.php')) && false ?: '_'});
