<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'validator.expression' shared service.

return $this->services['validator.expression'] = new \Symfony\Component\Validator\Constraints\ExpressionValidator();
