<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'validator.email' shared service.

return $this->services['validator.email'] = new \Symfony\Component\Validator\Constraints\EmailValidator(false);
