<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerH6zcps3\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerH6zcps3/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerH6zcps3.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerH6zcps3\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerH6zcps3\appProdProjectContainer([
    'container.build_hash' => 'H6zcps3',
    'container.build_id' => 'c4aff07a',
    'container.build_time' => 1614111319,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerH6zcps3');
