<?php

namespace Proxies\__CG__\PartKeepr\StockBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class StockEntry extends \PartKeepr\StockBundle\Entity\StockEntry implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'PartKeepr\\StockBundle\\Entity\\StockEntry' . "\0" . 'stockLevel', '' . "\0" . 'PartKeepr\\StockBundle\\Entity\\StockEntry' . "\0" . 'part', '' . "\0" . 'PartKeepr\\StockBundle\\Entity\\StockEntry' . "\0" . 'user', '' . "\0" . 'PartKeepr\\StockBundle\\Entity\\StockEntry' . "\0" . 'price', '' . "\0" . 'PartKeepr\\StockBundle\\Entity\\StockEntry' . "\0" . 'dateTime', '' . "\0" . 'PartKeepr\\StockBundle\\Entity\\StockEntry' . "\0" . 'correction', '' . "\0" . 'PartKeepr\\StockBundle\\Entity\\StockEntry' . "\0" . 'comment'];
        }

        return ['__isInitialized__', '' . "\0" . 'PartKeepr\\StockBundle\\Entity\\StockEntry' . "\0" . 'stockLevel', '' . "\0" . 'PartKeepr\\StockBundle\\Entity\\StockEntry' . "\0" . 'part', '' . "\0" . 'PartKeepr\\StockBundle\\Entity\\StockEntry' . "\0" . 'user', '' . "\0" . 'PartKeepr\\StockBundle\\Entity\\StockEntry' . "\0" . 'price', '' . "\0" . 'PartKeepr\\StockBundle\\Entity\\StockEntry' . "\0" . 'dateTime', '' . "\0" . 'PartKeepr\\StockBundle\\Entity\\StockEntry' . "\0" . 'correction', '' . "\0" . 'PartKeepr\\StockBundle\\Entity\\StockEntry' . "\0" . 'comment'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (StockEntry $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getDateTime()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateTime', []);

        return parent::getDateTime();
    }

    /**
     * {@inheritDoc}
     */
    public function setCorrection($bCorrection)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCorrection', [$bCorrection]);

        return parent::setCorrection($bCorrection);
    }

    /**
     * {@inheritDoc}
     */
    public function getCorrection()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCorrection', []);

        return parent::getCorrection();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrice($price)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrice', [$price]);

        return parent::setPrice($price);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrice()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrice', []);

        return parent::getPrice();
    }

    /**
     * {@inheritDoc}
     */
    public function setStockLevel($stockLevel)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStockLevel', [$stockLevel]);

        return parent::setStockLevel($stockLevel);
    }

    /**
     * {@inheritDoc}
     */
    public function getStockLevel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStockLevel', []);

        return parent::getStockLevel();
    }

    /**
     * {@inheritDoc}
     */
    public function setPart(\PartKeepr\PartBundle\Entity\Part $part = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPart', [$part]);

        return parent::setPart($part);
    }

    /**
     * {@inheritDoc}
     */
    public function getPart()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPart', []);

        return parent::getPart();
    }

    /**
     * {@inheritDoc}
     */
    public function setUser(\PartKeepr\AuthBundle\Entity\User $user = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUser', [$user]);

        return parent::setUser($user);
    }

    /**
     * {@inheritDoc}
     */
    public function getUser()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUser', []);

        return parent::getUser();
    }

    /**
     * {@inheritDoc}
     */
    public function checkPrice()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'checkPrice', []);

        return parent::checkPrice();
    }

    /**
     * {@inheritDoc}
     */
    public function isRemoval()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isRemoval', []);

        return parent::isRemoval();
    }

    /**
     * {@inheritDoc}
     */
    public function setComment($comment)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setComment', [$comment]);

        return parent::setComment($comment);
    }

    /**
     * {@inheritDoc}
     */
    public function getComment()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getComment', []);

        return parent::getComment();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

}
