<?php

namespace Proxies;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class deRaumZeitLaborPartDB2AuthUserProxy extends \de\RaumZeitLabor\PartDB2\Auth\User implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    private function _load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    
    public function setUsername($username)
    {
        $this->_load();
        return parent::setUsername($username);
    }

    public function getUsername()
    {
        $this->_load();
        return parent::getUsername();
    }

    public function setPassword($password)
    {
        $this->_load();
        return parent::setPassword($password);
    }

    public function getHashedPassword()
    {
        $this->_load();
        return parent::getHashedPassword();
    }

    public function setHashedPassword($hashedPassword)
    {
        $this->_load();
        return parent::setHashedPassword($hashedPassword);
    }

    public function comparePassword($password)
    {
        $this->_load();
        return parent::comparePassword($password);
    }

    public function compareHashedPassword($hashedPassword)
    {
        $this->_load();
        return parent::compareHashedPassword($hashedPassword);
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'username', 'password');
    }
}