<?php

namespace Proxies\__CG__\PartKeepr\PartBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class MetaPartParameterCriteria extends \PartKeepr\PartBundle\Entity\MetaPartParameterCriteria implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'PartKeepr\\PartBundle\\Entity\\MetaPartParameterCriteria' . "\0" . 'part', '' . "\0" . 'PartKeepr\\PartBundle\\Entity\\MetaPartParameterCriteria' . "\0" . 'partParameterName', '' . "\0" . 'PartKeepr\\PartBundle\\Entity\\MetaPartParameterCriteria' . "\0" . 'operator', '' . "\0" . 'PartKeepr\\PartBundle\\Entity\\MetaPartParameterCriteria' . "\0" . 'value', '' . "\0" . 'PartKeepr\\PartBundle\\Entity\\MetaPartParameterCriteria' . "\0" . 'normalizedValue', '' . "\0" . 'PartKeepr\\PartBundle\\Entity\\MetaPartParameterCriteria' . "\0" . 'siPrefix', '' . "\0" . 'PartKeepr\\PartBundle\\Entity\\MetaPartParameterCriteria' . "\0" . 'stringValue', '' . "\0" . 'PartKeepr\\PartBundle\\Entity\\MetaPartParameterCriteria' . "\0" . 'valueType', '' . "\0" . 'PartKeepr\\PartBundle\\Entity\\MetaPartParameterCriteria' . "\0" . 'unit'];
        }

        return ['__isInitialized__', '' . "\0" . 'PartKeepr\\PartBundle\\Entity\\MetaPartParameterCriteria' . "\0" . 'part', '' . "\0" . 'PartKeepr\\PartBundle\\Entity\\MetaPartParameterCriteria' . "\0" . 'partParameterName', '' . "\0" . 'PartKeepr\\PartBundle\\Entity\\MetaPartParameterCriteria' . "\0" . 'operator', '' . "\0" . 'PartKeepr\\PartBundle\\Entity\\MetaPartParameterCriteria' . "\0" . 'value', '' . "\0" . 'PartKeepr\\PartBundle\\Entity\\MetaPartParameterCriteria' . "\0" . 'normalizedValue', '' . "\0" . 'PartKeepr\\PartBundle\\Entity\\MetaPartParameterCriteria' . "\0" . 'siPrefix', '' . "\0" . 'PartKeepr\\PartBundle\\Entity\\MetaPartParameterCriteria' . "\0" . 'stringValue', '' . "\0" . 'PartKeepr\\PartBundle\\Entity\\MetaPartParameterCriteria' . "\0" . 'valueType', '' . "\0" . 'PartKeepr\\PartBundle\\Entity\\MetaPartParameterCriteria' . "\0" . 'unit'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (MetaPartParameterCriteria $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getNormalizedValue()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNormalizedValue', []);

        return parent::getNormalizedValue();
    }

    /**
     * {@inheritDoc}
     */
    public function setNormalizedValue($normalizedValue)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNormalizedValue', [$normalizedValue]);

        return parent::setNormalizedValue($normalizedValue);
    }

    /**
     * {@inheritDoc}
     */
    public function getUnit()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUnit', []);

        return parent::getUnit();
    }

    /**
     * {@inheritDoc}
     */
    public function setUnit($unit = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUnit', [$unit]);

        return parent::setUnit($unit);
    }

    /**
     * {@inheritDoc}
     */
    public function getValueType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getValueType', []);

        return parent::getValueType();
    }

    /**
     * {@inheritDoc}
     */
    public function setValueType($valueType)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setValueType', [$valueType]);

        return parent::setValueType($valueType);
    }

    /**
     * {@inheritDoc}
     */
    public function getSiPrefix()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSiPrefix', []);

        return parent::getSiPrefix();
    }

    /**
     * {@inheritDoc}
     */
    public function setSiPrefix($siPrefix)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSiPrefix', [$siPrefix]);

        return parent::setSiPrefix($siPrefix);
    }

    /**
     * {@inheritDoc}
     */
    public function getPart()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPart', []);

        return parent::getPart();
    }

    /**
     * {@inheritDoc}
     */
    public function setPart($part = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPart', [$part]);

        return parent::setPart($part);
    }

    /**
     * {@inheritDoc}
     */
    public function getPartParameterName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPartParameterName', []);

        return parent::getPartParameterName();
    }

    /**
     * {@inheritDoc}
     */
    public function setPartParameterName($partParameterName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPartParameterName', [$partParameterName]);

        return parent::setPartParameterName($partParameterName);
    }

    /**
     * {@inheritDoc}
     */
    public function getOperator()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOperator', []);

        return parent::getOperator();
    }

    /**
     * {@inheritDoc}
     */
    public function setOperator($operator)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOperator', [$operator]);

        return parent::setOperator($operator);
    }

    /**
     * {@inheritDoc}
     */
    public function getValue()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getValue', []);

        return parent::getValue();
    }

    /**
     * {@inheritDoc}
     */
    public function setValue($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setValue', [$value]);

        return parent::setValue($value);
    }

    /**
     * {@inheritDoc}
     */
    public function getStringValue()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStringValue', []);

        return parent::getStringValue();
    }

    /**
     * {@inheritDoc}
     */
    public function setStringValue($stringValue)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStringValue', [$stringValue]);

        return parent::setStringValue($stringValue);
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

}
